new PlayerText:td_leftann_title[MAX_PLAYERS];
new PlayerText:td_leftann_content[MAX_PLAYERS];
new PlayerText:td_leftann_ball[MAX_PLAYERS];
new PlayerText:td_leftann_icon[MAX_PLAYERS];

new PlayerText:hl_logon0[MAX_PLAYERS];
new PlayerText:hl_logon1[MAX_PLAYERS];


new Float:td_radiocar_offsetY = -72.0;
new PlayerText:td_radiocar0[MAX_PLAYERS];
new PlayerText:td_radiocar1[MAX_PLAYERS];
new PlayerText:td_radiocar2[MAX_PLAYERS];
new PlayerText:td_radiocar3[MAX_PLAYERS];
new PlayerText:td_radiocar4[MAX_PLAYERS];
new PlayerText:td_radiocar5[MAX_PLAYERS];
new PlayerText:td_radiocar6[MAX_PLAYERS];
new PlayerText:td_radiocar7[MAX_PLAYERS];
new PlayerText:td_radiocar8[MAX_PLAYERS];
new PlayerText:td_radiocar9[MAX_PLAYERS];
new PlayerText:td_radiocar10[MAX_PLAYERS];


new Float:td_carhud_offsetX = 284.0;
new Float:td_carhud_offsetY = 5.0;
new PlayerText:td_P_carhud0[MAX_PLAYERS];
new PlayerText:td_P_carhud1[MAX_PLAYERS];
new PlayerText:td_P_carhud2[MAX_PLAYERS];
new PlayerText:td_P_carhud3[MAX_PLAYERS];
new PlayerText:td_P_carhud4[MAX_PLAYERS];
new PlayerText:td_P_carhud5[MAX_PLAYERS];
new PlayerText:td_P_carhud6[MAX_PLAYERS];
new PlayerText:td_P_carhud7[MAX_PLAYERS];
new PlayerText:td_P_carhud8[MAX_PLAYERS];
new PlayerText:td_P_carhud9[MAX_PLAYERS];
new PlayerText:td_P_carhud10[MAX_PLAYERS];
new PlayerText:td_P_carhud11[MAX_PLAYERS];
new PlayerText:td_P_carhud12[MAX_PLAYERS];
new PlayerText:td_P_carhud13[MAX_PLAYERS];
new PlayerText:td_P_carhud14[MAX_PLAYERS];
new PlayerText:td_P_carhud15[MAX_PLAYERS];
new PlayerText:td_P_carhud16[MAX_PLAYERS];
new PlayerText:td_P_carhud17[MAX_PLAYERS];
new PlayerText:td_P_carhud18[MAX_PLAYERS];
new PlayerText:td_P_carhud19[MAX_PLAYERS];
new PlayerText:td_P_carhud20[MAX_PLAYERS];
new PlayerText:td_P_carhud21[MAX_PLAYERS];
new PlayerText:td_P_carhud22[MAX_PLAYERS];
new PlayerText:td_P_carhud23[MAX_PLAYERS];
new PlayerText:td_P_carhud24[MAX_PLAYERS];
new PlayerText:td_P_carhud25[MAX_PLAYERS];
new PlayerText:td_P_carhud26[MAX_PLAYERS];
new PlayerText:td_P_carhud27[MAX_PLAYERS];
new PlayerText:td_P_carhud28[MAX_PLAYERS];
new PlayerText:td_P_carhud29[MAX_PLAYERS];
new PlayerText:td_P_carhud30[MAX_PLAYERS];
new PlayerText:td_P_carhud31[MAX_PLAYERS];
new PlayerText:td_P_carhud32[MAX_PLAYERS];
new PlayerText:td_P_carhud33[MAX_PLAYERS];
new PlayerText:td_P_carhud34[MAX_PLAYERS];
new PlayerText:td_P_carhud35[MAX_PLAYERS];
new PlayerText:td_P_carhud36[MAX_PLAYERS];
new PlayerText:td_P_carhud37[MAX_PLAYERS];
new PlayerText:td_P_carhud38[MAX_PLAYERS];
new PlayerText:td_P_carhud39[MAX_PLAYERS];
new PlayerText:td_P_carhud40[MAX_PLAYERS];
new PlayerText:td_P_carhud41[MAX_PLAYERS];
new PlayerText:td_P_carhud42[MAX_PLAYERS];
new PlayerText:td_P_carhud43[MAX_PLAYERS];
new PlayerText:td_P_carhud44[MAX_PLAYERS];
new PlayerText:td_P_carhud45[MAX_PLAYERS];
new PlayerText:td_P_carhud46[MAX_PLAYERS];
new PlayerText:td_P_carhud47[MAX_PLAYERS];
new PlayerText:td_P_carhud48[MAX_PLAYERS];
new PlayerText:td_P_carhud49[MAX_PLAYERS];
new PlayerText:td_P_carhud50[MAX_PLAYERS];
new PlayerText:td_P_carhud51[MAX_PLAYERS];
new PlayerText:td_P_carhud52[MAX_PLAYERS];
new PlayerText:td_P_carhud53[MAX_PLAYERS];
new PlayerText:td_P_carhud54[MAX_PLAYERS];

new PlayerText:td_p_dystrybutor0[MAX_PLAYERS];
new PlayerText:td_p_dystrybutor1[MAX_PLAYERS];
new PlayerText:td_p_dystrybutor2[MAX_PLAYERS];
new PlayerText:td_p_dystrybutor3[MAX_PLAYERS];
new PlayerText:td_p_dystrybutor4[MAX_PLAYERS];
new PlayerText:td_p_dystrybutor5[MAX_PLAYERS];

new PlayerText:td_p_rightmsgbox0[MAX_PLAYERS];
new PlayerText:td_p_rightmsgbox1[MAX_PLAYERS];

new PlayerText:td_p_cargoinfo0[MAX_PLAYERS];
new PlayerText:td_p_cargoinfo1[MAX_PLAYERS];
new PlayerText:td_p_cargoinfo2[MAX_PLAYERS];
new PlayerText:td_p_cargoinfo3[MAX_PLAYERS];

new PlayerText:td_p_trucksalon0[MAX_PLAYERS];
new PlayerText:td_p_trucksalon1[MAX_PLAYERS];
new PlayerText:td_p_trucksalon2[MAX_PLAYERS];
new PlayerText:td_p_trucksalon3[MAX_PLAYERS];
new PlayerText:td_p_trucksalon4[MAX_PLAYERS];
new PlayerText:td_p_trucksalon5[MAX_PLAYERS];
new PlayerText:td_p_trucksalon6[MAX_PLAYERS];
new PlayerText:td_p_trucksalon7[MAX_PLAYERS];

new PlayerText:td_p_confirmcargo1[MAX_PLAYERS];
new PlayerText:td_p_confirmcargo2[MAX_PLAYERS];
new PlayerText:td_p_confirmcargo3[MAX_PLAYERS];
new PlayerText:td_p_confirmcargo4[MAX_PLAYERS];

new PlayerText:td_p_gpsdistance[MAX_PLAYERS];

new PlayerText:td_p_delivered0[MAX_PLAYERS];
new PlayerText:td_p_delivered1[MAX_PLAYERS];
new PlayerText:td_p_delivered2[MAX_PLAYERS];
new PlayerText:td_p_delivered3[MAX_PLAYERS];

new PlayerText:anntd[MAX_PLAYERS];

new PlayerText:td_p_saction0[MAX_PLAYERS];

new PlayerText:ftool0[MAX_PLAYERS];
new PlayerText:ftool1[MAX_PLAYERS];

new PlayerText:td_p_fullscreen[MAX_PLAYERS];

new PlayerText:td_p_taxi0[MAX_PLAYERS];
new PlayerText:td_p_taxi1[MAX_PLAYERS];
new PlayerText:td_p_taxi2[MAX_PLAYERS];

new PlayerText:td_p_dokument0[MAX_PLAYERS];
new PlayerText:td_p_dokument1[MAX_PLAYERS];
new PlayerText:td_p_dokument2[MAX_PLAYERS];

new PlayerText:td_p_adminspec0[MAX_PLAYERS];
new PlayerText:td_p_adminspec1[MAX_PLAYERS];

new PlayerText:tdCombine0[MAX_PLAYERS];
new PlayerText:tdCombine1[MAX_PLAYERS];
new PlayerText:tdCombine2[MAX_PLAYERS];
new PlayerText:tdCombine3[MAX_PLAYERS];
new PlayerText:tdCombine4[MAX_PLAYERS];
new PlayerText:tdCombine5[MAX_PLAYERS];
new PlayerText:tdCombine6[MAX_PLAYERS];
new PlayerText:tdCombine7[MAX_PLAYERS];
new PlayerText:tdCombine8[MAX_PLAYERS];

new PlayerText:td_p_pursuit0[MAX_PLAYERS];
new PlayerText:td_p_pursuit1[MAX_PLAYERS];
new PlayerText:td_p_pursuit2[MAX_PLAYERS];
new PlayerText:td_p_pursuit3[MAX_PLAYERS];
new PlayerText:td_p_pursuit4[MAX_PLAYERS];
new PlayerText:td_p_pursuit5[MAX_PLAYERS];
new PlayerText:td_p_pursuit6[MAX_PLAYERS];
new PlayerText:td_p_pursuit7[MAX_PLAYERS];
new PlayerText:td_p_pursuit8[MAX_PLAYERS];
new PlayerText:td_p_pursuit9[MAX_PLAYERS];
new PlayerText:td_p_pursuit10[MAX_PLAYERS];

new PlayerText:microactive[MAX_PLAYERS];

new PlayerText:td_p_simpletext[MAX_PLAYERS];

new PlayerText:td_p_limit0[MAX_PLAYERS];

new PlayerText:vhl_playerlist[MAX_PLAYERS];

new Text:panorama0;
new Text:panorama1;
new Text:logo_hl;

new Text:td_radiocar11;
new Text:td_radiocar12;
new Text:td_radiocar13;
new Text:td_radiocar14;

new Text:td_G_carhud0;
new Text:td_G_carhud1;
new Text:td_G_carhud2;
new Text:td_G_carhud3;
new Text:td_G_carhud4;
new Text:td_G_carhud5;
new Text:td_G_carhud6;
new Text:td_G_carhud7;
new Text:td_G_carhud8;
new Text:td_G_carhud9;
new Text:td_G_carhud10;
new Text:td_G_carhud11;
new Text:td_G_carhud12;
new Text:td_G_carhud13;
new Text:td_G_carhud14;
new Text:td_G_carhud15;
new Text:td_G_carhud16;
new Text:td_G_carhud17;
new Text:td_G_carhud18;
new Text:td_G_carhud19;
new Text:td_G_carhud20;
new Text:td_G_carhud21;
new Text:td_G_carhud22;
new Text:td_G_carhud23;
new Text:td_G_carhud24;

new Text:td_g_dystrybutor0;
new Text:td_g_dystrybutor1;
new Text:td_g_dystrybutor2;
new Text:td_g_dystrybutor3;
new Text:td_g_dystrybutor4;
new Text:td_g_dystrybutor5;
new Text:td_g_dystrybutor6;
new Text:td_g_dystrybutor7;
new Text:td_g_dystrybutor8;
new Text:td_g_dystrybutor9;
new Text:td_g_dystrybutor10;
new Text:td_g_dystrybutor11;
new Text:td_g_dystrybutor12;
new Text:td_g_dystrybutor13;
new Text:td_g_dystrybutor14;
new Text:td_g_dystrybutor15;
new Text:td_g_dystrybutor16;
new Text:td_g_dystrybutor17;
new Text:td_g_dystrybutor18;
new Text:td_g_dystrybutor19;
new Text:td_g_dystrybutor20;

new Text:td_g_rightmsgbox0;

new Text:td_g_cargoinfo0;
new Text:td_g_cargoinfo1;
new Text:td_g_cargoinfo2;
new Text:td_g_cargoinfo3;
new Text:td_g_cargoinfo4;
new Text:td_g_cargoinfo5;

new Text:td_g_trucksalon0;
new Text:td_g_trucksalon1;
new Text:td_g_trucksalon2;
new Text:td_g_trucksalon3;

new Text:td_g_confirmcargo0;
new Text:td_g_confirmcargo1;
new Text:td_g_confirmcargo2;
new Text:td_g_confirmcargo3;
new Text:td_g_confirmcargo4;
new Text:td_g_confirmcargo5;
new Text:td_g_confirmcargo6;

new Text:td_g_delivered0;
new Text:td_g_delivered1;
new Text:td_g_delivered2;
new Text:td_g_delivered3;
new Text:td_g_delivered4;
new Text:td_g_delivered5;
new Text:td_g_delivered6;
new Text:td_g_delivered7;
new Text:td_g_delivered8;

new Text:td_g_saction0;
new Text:td_g_saction1;

new Text:td_g_taxi0;
new Text:td_g_taxi1;
new Text:td_g_taxi2;
new Text:td_g_taxi3;
new Text:td_g_taxi4;
new Text:td_g_taxi5;

new Text:td_g_dokument0;
new Text:td_g_dokument1;
new Text:td_g_dokument2;
new Text:td_g_dokument3;
new Text:td_g_dokument4;
new Text:td_g_dokument5;
new Text:td_g_dokument6;
new Text:td_g_dokument7;

new Text:td_g_shoot0;
new Text:td_g_shoot1;

new Text:td_g_limit0;
new Text:td_g_limit1;

stock Init_TextDrawPlayerDynamic(playerid)
{
	td_leftann_title[playerid] = CreatePlayerTextDraw(playerid, 18.000000, 206.937500, "Misja");
	PlayerTextDrawLetterSize(playerid, td_leftann_title[playerid], 0.440499, 1.573750);
	PlayerTextDrawAlignment(playerid, td_leftann_title[playerid], 1);
	PlayerTextDrawColor(playerid, td_leftann_title[playerid], -2147483393);
	PlayerTextDrawSetShadow(playerid, td_leftann_title[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_leftann_title[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_leftann_title[playerid], 51);
	PlayerTextDrawFont(playerid, td_leftann_title[playerid], 0);
	PlayerTextDrawSetProportional(playerid, td_leftann_title[playerid], 1);

	td_leftann_content[playerid] = CreatePlayerTextDraw(playerid, 10.500000, 217.875000, "~n~NONE");
	PlayerTextDrawLetterSize(playerid, td_leftann_content[playerid], 0.219999, 0.865000);
	PlayerTextDrawTextSize(playerid, td_leftann_content[playerid], 127.500000, -63.437500);
	PlayerTextDrawAlignment(playerid, td_leftann_content[playerid], 1);
	PlayerTextDrawColor(playerid, td_leftann_content[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_leftann_content[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_leftann_content[playerid], 80);
	PlayerTextDrawSetShadow(playerid, td_leftann_content[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_leftann_content[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_leftann_content[playerid], 48);
	PlayerTextDrawFont(playerid, td_leftann_content[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_leftann_content[playerid], 1);

	td_leftann_ball[playerid] = CreatePlayerTextDraw(playerid, 1.000000, 210.875000, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_leftann_ball[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_leftann_ball[playerid], 15.000000, 11.375000);
	PlayerTextDrawAlignment(playerid, td_leftann_ball[playerid], 1);
	PlayerTextDrawColor(playerid, td_leftann_ball[playerid], -2147483393);
	PlayerTextDrawSetShadow(playerid, td_leftann_ball[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_leftann_ball[playerid], 0);
	PlayerTextDrawFont(playerid, td_leftann_ball[playerid], 4);

	td_leftann_icon[playerid] = CreatePlayerTextDraw(playerid, 6.500000, 210.437500, "!");
	PlayerTextDrawLetterSize(playerid, td_leftann_icon[playerid], 0.434500, 1.258749);
	PlayerTextDrawAlignment(playerid, td_leftann_icon[playerid], 1);
	PlayerTextDrawColor(playerid, td_leftann_icon[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_leftann_icon[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_leftann_icon[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_leftann_icon[playerid], 51);
	PlayerTextDrawFont(playerid, td_leftann_icon[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_leftann_icon[playerid], 1);

	hl_logon0[playerid] = CreatePlayerTextDraw(playerid, 184.888671, 105.031150, "Highway");
	PlayerTextDrawLetterSize(playerid, hl_logon0[playerid], 1.232667, 3.571196);
	PlayerTextDrawAlignment(playerid, hl_logon0[playerid], 1);
	PlayerTextDrawColor(playerid, hl_logon0[playerid], 41215);
	PlayerTextDrawSetShadow(playerid, hl_logon0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, hl_logon0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, hl_logon0[playerid], 51);
	PlayerTextDrawFont(playerid, hl_logon0[playerid], 3);
	PlayerTextDrawSetProportional(playerid, hl_logon0[playerid], 1);

	hl_logon1[playerid] = CreatePlayerTextDraw(playerid, 338.778350, 139.880157, "Life");
	PlayerTextDrawLetterSize(playerid, hl_logon1[playerid], 1.251334, 3.795196);
	PlayerTextDrawAlignment(playerid, hl_logon1[playerid], 1);
	PlayerTextDrawColor(playerid, hl_logon1[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, hl_logon1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, hl_logon1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, hl_logon1[playerid], 51);
	PlayerTextDrawFont(playerid, hl_logon1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, hl_logon1[playerid], 1);

	td_radiocar0[playerid] = CreatePlayerTextDraw(playerid, 545.222534, 390.271087+td_radiocar_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_radiocar0[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_radiocar0[playerid], 91.733360, 11.448880);
	PlayerTextDrawAlignment(playerid, td_radiocar0[playerid], 1);
	PlayerTextDrawColor(playerid, td_radiocar0[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_radiocar0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar0[playerid], 0);
	PlayerTextDrawFont(playerid, td_radiocar0[playerid], 4);
	PlayerTextDrawSetProportional(playerid, td_radiocar0[playerid], 1);

	td_radiocar1[playerid] = CreatePlayerTextDraw(playerid, 590.955688, 392.203460+td_radiocar_offsetY, "88888888888888888888");
	PlayerTextDrawLetterSize(playerid, td_radiocar1[playerid], 0.162444, 0.863288);
	PlayerTextDrawAlignment(playerid, td_radiocar1[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar1[playerid], 41215);
	PlayerTextDrawSetShadow(playerid, td_radiocar1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar1[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar1[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar1[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_radiocar1[playerid], 1);

	td_radiocar2[playerid] = CreatePlayerTextDraw(playerid, 513.333312, 387.786865+td_radiocar_offsetY, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_radiocar2[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_radiocar2[playerid], 24.888927, 21.404447);
	PlayerTextDrawAlignment(playerid, td_radiocar2[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar2[playerid], -2139062017);
	PlayerTextDrawSetShadow(playerid, td_radiocar2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar2[playerid], 0);
	PlayerTextDrawFont(playerid, td_radiocar2[playerid], 4);
	PlayerTextDrawSetProportional(playerid, td_radiocar2[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar2[playerid], true);

	td_radiocar3[playerid] = CreatePlayerTextDraw(playerid, 516.556030, 390.330108+td_radiocar_offsetY, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_radiocar3[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_radiocar3[playerid], 18.666702, 16.426668);
	PlayerTextDrawAlignment(playerid, td_radiocar3[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar3[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar3[playerid], 0);
	PlayerTextDrawFont(playerid, td_radiocar3[playerid], 4);
	PlayerTextDrawSetProportional(playerid, td_radiocar3[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar3[playerid], true);

	td_radiocar4[playerid] = CreatePlayerTextDraw(playerid, 551.156921, 405.250000+td_radiocar_offsetY, "1");
	PlayerTextDrawLetterSize(playerid, td_radiocar4[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar4[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar4[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar4[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar4[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar4[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar4[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar4[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar4[playerid], true);

	td_radiocar5[playerid] = CreatePlayerTextDraw(playerid, 564.512145, 405.195800+td_radiocar_offsetY, "2");
	PlayerTextDrawLetterSize(playerid, td_radiocar5[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar5[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar5[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar5[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar5[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar5[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar5[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar5[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar5[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar5[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar5[playerid], true);

	td_radiocar6[playerid] = CreatePlayerTextDraw(playerid, 578.045654, 405.349456+td_radiocar_offsetY, "3");
	PlayerTextDrawLetterSize(playerid, td_radiocar6[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar6[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar6[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar6[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar6[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar6[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar6[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar6[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar6[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar6[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar6[playerid], true);

	td_radiocar7[playerid] = CreatePlayerTextDraw(playerid, 591.268371, 405.304138+td_radiocar_offsetY, "4");
	PlayerTextDrawLetterSize(playerid, td_radiocar7[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar7[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar7[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar7[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar7[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar7[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar7[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar7[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar7[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar7[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar7[playerid], true);

	td_radiocar8[playerid] = CreatePlayerTextDraw(playerid, 604.446044, 405.209075+td_radiocar_offsetY, "5");
	PlayerTextDrawLetterSize(playerid, td_radiocar8[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar8[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar8[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar8[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar8[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar8[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar8[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar8[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar8[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar8[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar8[playerid], true);

	td_radiocar9[playerid] = CreatePlayerTextDraw(playerid, 617.446044, 405.213562+td_radiocar_offsetY, "6");
	PlayerTextDrawLetterSize(playerid, td_radiocar9[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar9[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar9[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar9[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar9[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar9[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar9[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar9[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar9[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar9[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar9[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar9[playerid], true);

	td_radiocar10[playerid] = CreatePlayerTextDraw(playerid, 630.757141, 405.267883+td_radiocar_offsetY, "EX");
	PlayerTextDrawLetterSize(playerid, td_radiocar10[playerid], 0.198888, 0.534756);
	PlayerTextDrawTextSize(playerid, td_radiocar10[playerid], 15.000000, -15.928786);
	PlayerTextDrawAlignment(playerid, td_radiocar10[playerid], 2);
	PlayerTextDrawColor(playerid, td_radiocar10[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_radiocar10[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_radiocar10[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_radiocar10[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_radiocar10[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_radiocar10[playerid], 51);
	PlayerTextDrawFont(playerid, td_radiocar10[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_radiocar10[playerid], 1);
	//PlayerTextDrawSetSelectable(playerid, td_radiocar10[playerid], true);


	td_P_carhud0[playerid] = CreatePlayerTextDraw(playerid, 156.888916+td_carhud_offsetX, 398.222259+td_carhud_offsetY, "0");
	PlayerTextDrawLetterSize(playerid, td_P_carhud0[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud0[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud0[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud0[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud0[playerid], 1);

	td_P_carhud1[playerid] = CreatePlayerTextDraw(playerid, 152.111160+td_carhud_offsetX, 391.257843+td_carhud_offsetY, "20");
	PlayerTextDrawLetterSize(playerid, td_P_carhud1[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud1[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud1[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud1[playerid], 1);

	td_P_carhud2[playerid] = CreatePlayerTextDraw(playerid, 150.000030+td_carhud_offsetX, 382.800170+td_carhud_offsetY, "40");
	PlayerTextDrawLetterSize(playerid, td_P_carhud2[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud2[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud2[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud2[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud2[playerid], 1);

	td_P_carhud3[playerid] = CreatePlayerTextDraw(playerid, 149.666702+td_carhud_offsetX, 373.844604+td_carhud_offsetY, "60");
	PlayerTextDrawLetterSize(playerid, td_P_carhud3[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud3[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud3[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud3[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud3[playerid], 1);

	td_P_carhud4[playerid] = CreatePlayerTextDraw(playerid, 152.444473+td_carhud_offsetX, 364.889068+td_carhud_offsetY, "80");
	PlayerTextDrawLetterSize(playerid, td_P_carhud4[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud4[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud4[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud4[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud4[playerid], 1);

	td_P_carhud5[playerid] = CreatePlayerTextDraw(playerid, 156.555572+td_carhud_offsetX, 356.929046+td_carhud_offsetY, "100");
	PlayerTextDrawLetterSize(playerid, td_P_carhud5[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud5[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud5[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud5[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud5[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud5[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud5[playerid], 1);

	td_P_carhud6[playerid] = CreatePlayerTextDraw(playerid, 163.777786+td_carhud_offsetX, 350.960174+td_carhud_offsetY, "120");
	PlayerTextDrawLetterSize(playerid, td_P_carhud6[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud6[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud6[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud6[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud6[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud6[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud6[playerid], 1);

	td_P_carhud7[playerid] = CreatePlayerTextDraw(playerid, 173.800018+td_carhud_offsetX, 348.027679+td_carhud_offsetY, "140");
	PlayerTextDrawLetterSize(playerid, td_P_carhud7[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud7[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud7[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud7[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud7[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud7[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud7[playerid], 1);

	td_P_carhud8[playerid] = CreatePlayerTextDraw(playerid, 183.733276+td_carhud_offsetX, 348.131805+td_carhud_offsetY, "160");
	PlayerTextDrawLetterSize(playerid, td_P_carhud8[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud8[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud8[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud8[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud8[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud8[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud8[playerid], 1);

	td_P_carhud9[playerid] = CreatePlayerTextDraw(playerid, 193.577743+td_carhud_offsetX, 351.272186+td_carhud_offsetY, "180");
	PlayerTextDrawLetterSize(playerid, td_P_carhud9[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud9[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud9[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud9[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud9[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud9[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud9[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud9[playerid], 1);

	td_P_carhud10[playerid] = CreatePlayerTextDraw(playerid, 201.555496+td_carhud_offsetX, 357.697967+td_carhud_offsetY, "200");
	PlayerTextDrawLetterSize(playerid, td_P_carhud10[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud10[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud10[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud10[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud10[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud10[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud10[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud10[playerid], 1);

	td_P_carhud11[playerid] = CreatePlayerTextDraw(playerid, 206.333328+td_carhud_offsetX, 365.915740+td_carhud_offsetY, "210");
	PlayerTextDrawLetterSize(playerid, td_P_carhud11[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud11[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud11[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud11[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud11[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud11[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud11[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud11[playerid], 1);

	td_P_carhud12[playerid] = CreatePlayerTextDraw(playerid, 208.577697+td_carhud_offsetX, 374.979675+td_carhud_offsetY, "220");
	PlayerTextDrawLetterSize(playerid, td_P_carhud12[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud12[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud12[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud12[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud12[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud12[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud12[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud12[playerid], 1);

	td_P_carhud13[playerid] = CreatePlayerTextDraw(playerid, 208.511062+td_carhud_offsetX, 384.043548+td_carhud_offsetY, "230");
	PlayerTextDrawLetterSize(playerid, td_P_carhud13[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud13[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud13[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud13[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud13[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud13[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud13[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud13[playerid], 1);

	td_P_carhud14[playerid] = CreatePlayerTextDraw(playerid, 206.044418+td_carhud_offsetX, 392.311126+td_carhud_offsetY, "240");
	PlayerTextDrawLetterSize(playerid, td_P_carhud14[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud14[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud14[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud14[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud14[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud14[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud14[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud14[playerid], 1);

	td_P_carhud15[playerid] = CreatePlayerTextDraw(playerid, 201.622131+td_carhud_offsetX, 399.732513+td_carhud_offsetY, "250");
	PlayerTextDrawLetterSize(playerid, td_P_carhud15[playerid], 0.120222, 0.569598);
	PlayerTextDrawAlignment(playerid, td_P_carhud15[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud15[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud15[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud15[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud15[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud15[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud15[playerid], 1);

	td_P_carhud16[playerid] = CreatePlayerTextDraw(playerid, 160.355529+td_carhud_offsetX, 385.628387+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud16[playerid], 0.000222, -0.009955);
	PlayerTextDrawTextSize(playerid, td_P_carhud16[playerid], 36.577774, 11.598216);
	PlayerTextDrawAlignment(playerid, td_P_carhud16[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud16[playerid], -1958346497);
	PlayerTextDrawSetShadow(playerid, td_P_carhud16[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud16[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud16[playerid], 4);

	td_P_carhud17[playerid] = CreatePlayerTextDraw(playerid, 178.266693+td_carhud_offsetX, 385.279968+td_carhud_offsetY, "300 km/h");
	PlayerTextDrawLetterSize(playerid, td_P_carhud17[playerid], 0.185155, 1.161954);
	PlayerTextDrawAlignment(playerid, td_P_carhud17[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud17[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_P_carhud17[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud17[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud17[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud17[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud17[playerid], 1);

	td_P_carhud18[playerid] = CreatePlayerTextDraw(playerid, 179.866699+td_carhud_offsetX, 362.730743+td_carhud_offsetY, "LD_BEAT:right");
	PlayerTextDrawLetterSize(playerid, td_P_carhud18[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud18[playerid], 9.733325, 6.570660);
	PlayerTextDrawAlignment(playerid, td_P_carhud18[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud18[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_P_carhud18[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud18[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud18[playerid], 4);

	td_P_carhud19[playerid] = CreatePlayerTextDraw(playerid, 166.688934+td_carhud_offsetX, 362.784973+td_carhud_offsetY, "LD_BEAT:left");
	PlayerTextDrawLetterSize(playerid, td_P_carhud19[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud19[playerid], 9.733325, 6.570660);
	PlayerTextDrawAlignment(playerid, td_P_carhud19[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud19[playerid], 808464639);
	PlayerTextDrawSetShadow(playerid, td_P_carhud19[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud19[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud19[playerid], 4);

	td_P_carhud20[playerid] = CreatePlayerTextDraw(playerid, 179.288818+td_carhud_offsetX, 371.939514+td_carhud_offsetY, "D");
	PlayerTextDrawLetterSize(playerid, td_P_carhud20[playerid], 0.193644, 1.053436);
	PlayerTextDrawAlignment(playerid, td_P_carhud20[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud20[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_P_carhud20[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud20[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud20[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud20[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_P_carhud20[playerid], 1);

	td_P_carhud21[playerid] = CreatePlayerTextDraw(playerid, 170.466613+td_carhud_offsetX, 374.034759+td_carhud_offsetY, "/");
	PlayerTextDrawLetterSize(playerid, td_P_carhud21[playerid], 0.616042, 0.494931);
	PlayerTextDrawAlignment(playerid, td_P_carhud21[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud21[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_P_carhud21[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud21[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud21[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud21[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_P_carhud21[playerid], 1);

	td_P_carhud22[playerid] = CreatePlayerTextDraw(playerid, 170.355499+td_carhud_offsetX, 376.080078+td_carhud_offsetY, "/");
	PlayerTextDrawLetterSize(playerid, td_P_carhud22[playerid], 0.616042, 0.494931);
	PlayerTextDrawAlignment(playerid, td_P_carhud22[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud22[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_P_carhud22[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud22[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud22[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud22[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_P_carhud22[playerid], 1);

	td_P_carhud23[playerid] = CreatePlayerTextDraw(playerid, 170.600143+td_carhud_offsetX, 377.876464+td_carhud_offsetY, "/");
	PlayerTextDrawLetterSize(playerid, td_P_carhud23[playerid], 0.616042, 0.494931);
	PlayerTextDrawAlignment(playerid, td_P_carhud23[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud23[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_P_carhud23[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud23[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud23[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud23[playerid], 0);
	PlayerTextDrawSetProportional(playerid, td_P_carhud23[playerid], 1);

	td_P_carhud24[playerid] = CreatePlayerTextDraw(playerid, 222.533279+td_carhud_offsetX, 411.313690+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud24[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud24[playerid], 4.622220, 5.973305);
	PlayerTextDrawAlignment(playerid, td_P_carhud24[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud24[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud24[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud24[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud24[playerid], 4);

	td_P_carhud25[playerid] = CreatePlayerTextDraw(playerid, 222.644393+td_carhud_offsetX, 407.335968+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud25[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud25[playerid], 0.577775, 6.023083);
	PlayerTextDrawAlignment(playerid, td_P_carhud25[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud25[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud25[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud25[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud25[playerid], 4);

	td_P_carhud26[playerid] = CreatePlayerTextDraw(playerid, 226.622177+td_carhud_offsetX, 407.240905+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud26[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud26[playerid], 0.577775, 6.023083);
	PlayerTextDrawAlignment(playerid, td_P_carhud26[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud26[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud26[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud26[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud26[playerid], 4);

	td_P_carhud27[playerid] = CreatePlayerTextDraw(playerid, 222.866592+td_carhud_offsetX, 407.344818+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud27[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud27[playerid], 4.133327, 1.294193);
	PlayerTextDrawAlignment(playerid, td_P_carhud27[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud27[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud27[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud27[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud27[playerid], 4);

	td_P_carhud28[playerid] = CreatePlayerTextDraw(playerid, 226.311065+td_carhud_offsetX, 408.575988+td_carhud_offsetY, ")");
	PlayerTextDrawLetterSize(playerid, td_P_carhud28[playerid], 0.325955, 0.914559);
	PlayerTextDrawAlignment(playerid, td_P_carhud28[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud28[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud28[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud28[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud28[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud28[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud28[playerid], 1);

	td_P_carhud29[playerid] = CreatePlayerTextDraw(playerid, 223.377777+td_carhud_offsetX, 402.552703+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud29[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud29[playerid], 2.844326, -50.126239);
	PlayerTextDrawAlignment(playerid, td_P_carhud29[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud29[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud29[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud29[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud29[playerid], 4);

	td_P_carhud30[playerid] = CreatePlayerTextDraw(playerid, 331.444458+td_carhud_offsetX, 402.955352+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud30[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud30[playerid], 2.844326, -50.126239);
	PlayerTextDrawAlignment(playerid, td_P_carhud30[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud30[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud30[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud30[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud30[playerid], 4);

	td_P_carhud31[playerid] = CreatePlayerTextDraw(playerid, 332.133544+td_carhud_offsetX, 408.675689+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud31[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud31[playerid], 1.466662, 9.258665);
	PlayerTextDrawAlignment(playerid, td_P_carhud31[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud31[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud31[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud31[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud31[playerid], 4);

	td_P_carhud32[playerid] = CreatePlayerTextDraw(playerid, 331.133636+td_carhud_offsetX, 415.649230+td_carhud_offsetY, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_P_carhud32[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud32[playerid], 3.999993, 3.185775);
	PlayerTextDrawAlignment(playerid, td_P_carhud32[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud32[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud32[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud32[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud32[playerid], 4);

	td_P_carhud33[playerid] = CreatePlayerTextDraw(playerid, 333.267120+td_carhud_offsetX, 409.376953+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud33[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud33[playerid], 2.755548, 0.945770);
	PlayerTextDrawAlignment(playerid, td_P_carhud33[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud33[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud33[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud33[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud33[playerid], 4);

	td_P_carhud34[playerid] = CreatePlayerTextDraw(playerid, 333.644927+td_carhud_offsetX, 411.272918+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud34[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud34[playerid], 2.755548, 0.945770);
	PlayerTextDrawAlignment(playerid, td_P_carhud34[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud34[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud34[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud34[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud34[playerid], 4);

	td_P_carhud35[playerid] = CreatePlayerTextDraw(playerid, 333.489410+td_carhud_offsetX, 413.367950+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud35[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud35[playerid], 2.755548, 0.945770);
	PlayerTextDrawAlignment(playerid, td_P_carhud35[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud35[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_P_carhud35[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud35[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud35[playerid], 4);

	td_P_carhud36[playerid] = CreatePlayerTextDraw(playerid, 248.622192+td_carhud_offsetX, 404.842773+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud36[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud36[playerid], 67.555519, 11.946640);
	PlayerTextDrawAlignment(playerid, td_P_carhud36[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud36[playerid], -2139094785);
	PlayerTextDrawSetShadow(playerid, td_P_carhud36[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud36[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud36[playerid], 4);

	td_P_carhud37[playerid] = CreatePlayerTextDraw(playerid, 283.377990+td_carhud_offsetX, 404.593719+td_carhud_offsetY, "1234567890 KM");
	PlayerTextDrawLetterSize(playerid, td_P_carhud37[playerid], 0.193377, 1.269971);
	PlayerTextDrawAlignment(playerid, td_P_carhud37[playerid], 2);
	PlayerTextDrawColor(playerid, td_P_carhud37[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_P_carhud37[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud37[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud37[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud37[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_P_carhud37[playerid], 1);

	td_P_carhud38[playerid] = CreatePlayerTextDraw(playerid, 269.288787+td_carhud_offsetX, 354.666534+td_carhud_offsetY, "SERVICE");
	PlayerTextDrawLetterSize(playerid, td_P_carhud38[playerid], 0.158840, 0.716938);
	PlayerTextDrawAlignment(playerid, td_P_carhud38[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud38[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_P_carhud38[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud38[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud38[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud38[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_P_carhud38[playerid], 1);

	td_P_carhud39[playerid] = CreatePlayerTextDraw(playerid, 267.200103+td_carhud_offsetX, 354.119171+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud39[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud39[playerid], 0.933327, 7.864892);
	PlayerTextDrawAlignment(playerid, td_P_carhud39[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud39[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_P_carhud39[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud39[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud39[playerid], 4);

	td_P_carhud40[playerid] = CreatePlayerTextDraw(playerid, 267.222351+td_carhud_offsetX, 361.590362+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud40[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud40[playerid], 29.644430, 0.846229);
	PlayerTextDrawAlignment(playerid, td_P_carhud40[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud40[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_P_carhud40[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud40[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud40[playerid], 4);

	td_P_carhud41[playerid] = CreatePlayerTextDraw(playerid, 296.111145+td_carhud_offsetX, 354.770751+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud41[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud41[playerid], 0.933327, 7.864892);
	PlayerTextDrawAlignment(playerid, td_P_carhud41[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud41[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_P_carhud41[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud41[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud41[playerid], 4);

	td_P_carhud42[playerid] = CreatePlayerTextDraw(playerid, 267.511322+td_carhud_offsetX, 354.277496+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud42[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud42[playerid], 29.644430, 0.846229);
	PlayerTextDrawAlignment(playerid, td_P_carhud42[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud42[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_P_carhud42[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud42[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud42[playerid], 4);

	td_P_carhud43[playerid] = CreatePlayerTextDraw(playerid, 254.488754+td_carhud_offsetX, 369.450836+td_carhud_offsetY, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_P_carhud43[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud43[playerid], 8.133330, 9.208884);
	PlayerTextDrawAlignment(playerid, td_P_carhud43[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud43[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud43[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud43[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud43[playerid], 4);

	td_P_carhud44[playerid] = CreatePlayerTextDraw(playerid, 255.444305+td_carhud_offsetX, 370.550323+td_carhud_offsetY, "LD_POOL:ball");
	PlayerTextDrawLetterSize(playerid, td_P_carhud44[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud44[playerid], 6.311109, 7.267549);
	PlayerTextDrawAlignment(playerid, td_P_carhud44[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud44[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_P_carhud44[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud44[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud44[playerid], 4);

	td_P_carhud45[playerid] = CreatePlayerTextDraw(playerid, 256.799926+td_carhud_offsetX, 370.197143+td_carhud_offsetY, "P");
	PlayerTextDrawLetterSize(playerid, td_P_carhud45[playerid], 0.218133, 0.798080);
	PlayerTextDrawAlignment(playerid, td_P_carhud45[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud45[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud45[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud45[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud45[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud45[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud45[playerid], 1);

	td_P_carhud46[playerid] = CreatePlayerTextDraw(playerid, 252.555496+td_carhud_offsetX, 368.758148+td_carhud_offsetY, "(__)");
	PlayerTextDrawLetterSize(playerid, td_P_carhud46[playerid], 0.220486, 0.954877);
	PlayerTextDrawAlignment(playerid, td_P_carhud46[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud46[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud46[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud46[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud46[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud46[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud46[playerid], 1);

	td_P_carhud47[playerid] = CreatePlayerTextDraw(playerid, 299.421783+td_carhud_offsetX, 369.998229+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud47[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud47[playerid], 12.888879, 0.497801);
	PlayerTextDrawAlignment(playerid, td_P_carhud47[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud47[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud47[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud47[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud47[playerid], 4);

	td_P_carhud48[playerid] = CreatePlayerTextDraw(playerid, 299.444091+td_carhud_offsetX, 377.369689+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud48[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud48[playerid], 12.888879, 0.497801);
	PlayerTextDrawAlignment(playerid, td_P_carhud48[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud48[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud48[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud48[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud48[playerid], 4);

	td_P_carhud49[playerid] = CreatePlayerTextDraw(playerid, 299.333007+td_carhud_offsetX, 370.106628+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud49[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud49[playerid], 0.711107, 7.466691);
	PlayerTextDrawAlignment(playerid, td_P_carhud49[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud49[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud49[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud49[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud49[playerid], 4);

	td_P_carhud50[playerid] = CreatePlayerTextDraw(playerid, 311.444000+td_carhud_offsetX, 369.862274+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud50[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud50[playerid], 0.711107, 7.466691);
	PlayerTextDrawAlignment(playerid, td_P_carhud50[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud50[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud50[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud50[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud50[playerid], 4);

	td_P_carhud51[playerid] = CreatePlayerTextDraw(playerid, 301.910705+td_carhud_offsetX, 368.671997+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud51[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud51[playerid], 1.911105, 1.393803);
	PlayerTextDrawAlignment(playerid, td_P_carhud51[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud51[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud51[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud51[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud51[playerid], 4);

	td_P_carhud52[playerid] = CreatePlayerTextDraw(playerid, 307.799743+td_carhud_offsetX, 368.477294+td_carhud_offsetY, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_P_carhud52[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_P_carhud52[playerid], 1.911105, 1.393803);
	PlayerTextDrawAlignment(playerid, td_P_carhud52[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud52[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud52[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud52[playerid], 0);
	PlayerTextDrawFont(playerid, td_P_carhud52[playerid], 4);

	td_P_carhud53[playerid] = CreatePlayerTextDraw(playerid, 301.244293+td_carhud_offsetX, 370.495910+td_carhud_offsetY, "-  +");
	PlayerTextDrawLetterSize(playerid, td_P_carhud53[playerid], 0.144620, 0.506878);
	PlayerTextDrawAlignment(playerid, td_P_carhud53[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud53[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_P_carhud53[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud53[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud53[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud53[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud53[playerid], 1);

	td_P_carhud54[playerid] = CreatePlayerTextDraw(playerid, 252.711013+td_carhud_offsetX, 388.864196+td_carhud_offsetY, "N2O: lllllllllllllll");
	PlayerTextDrawLetterSize(playerid, td_P_carhud54[playerid], 0.188087, 0.653724);
	PlayerTextDrawAlignment(playerid, td_P_carhud54[playerid], 1);
	PlayerTextDrawColor(playerid, td_P_carhud54[playerid], 12189695);
	PlayerTextDrawSetShadow(playerid, td_P_carhud54[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_P_carhud54[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_P_carhud54[playerid], 51);
	PlayerTextDrawFont(playerid, td_P_carhud54[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_P_carhud54[playerid], 1);

	td_p_dystrybutor0[playerid] = CreatePlayerTextDraw(playerid, 314.844390, 157.397338, "0.00");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor0[playerid], 0.170576, 1.181865);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor0[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_dystrybutor0[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dystrybutor0[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_dystrybutor0[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_dystrybutor0[playerid], 1);

	td_p_dystrybutor1[playerid] = CreatePlayerTextDraw(playerid, 314.777618, 171.638229, "0.00");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor1[playerid], 0.170576, 1.181865);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor1[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_dystrybutor1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dystrybutor1[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_dystrybutor1[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_dystrybutor1[playerid], 1);

	td_p_dystrybutor2[playerid] = CreatePlayerTextDraw(playerid, 314.444458, 186.476470, "5.00");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor2[playerid], 0.170576, 1.181865);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor2[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_dystrybutor2[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dystrybutor2[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_dystrybutor2[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_dystrybutor2[playerid], 1);

	td_p_dystrybutor3[playerid] = CreatePlayerTextDraw(playerid, 305.977661, 223.805328, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor3[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_p_dystrybutor3[playerid], 21.866674, 21.105791);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor3[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_dystrybutor3[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor3[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_dystrybutor3[playerid], 4);

	td_p_dystrybutor4[playerid] = CreatePlayerTextDraw(playerid, 316.933227, 226.588378, "ON");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor4[playerid], 0.302799, 1.568142);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor4[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_dystrybutor4[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dystrybutor4[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_dystrybutor4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_dystrybutor4[playerid], 1);

	td_p_dystrybutor5[playerid] = CreatePlayerTextDraw(playerid, 314.177856, 143.359985, "ORLEN");
	PlayerTextDrawLetterSize(playerid, td_p_dystrybutor5[playerid], 0.388088, 0.968319);
	PlayerTextDrawAlignment(playerid, td_p_dystrybutor5[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_dystrybutor5[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_p_dystrybutor5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dystrybutor5[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dystrybutor5[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_dystrybutor5[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_dystrybutor5[playerid], 1);

	td_p_rightmsgbox0[playerid] = CreatePlayerTextDraw(playerid, 538.399719, 138.680923, "tresc");
	PlayerTextDrawLetterSize(playerid, td_p_rightmsgbox0[playerid], 0.181377, 0.874239);
	PlayerTextDrawTextSize(playerid, td_p_rightmsgbox0[playerid], 635.111083, 9.457789);
	PlayerTextDrawAlignment(playerid, td_p_rightmsgbox0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_rightmsgbox0[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_p_rightmsgbox0[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_rightmsgbox0[playerid], 85);
	PlayerTextDrawSetShadow(playerid, td_p_rightmsgbox0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_rightmsgbox0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_rightmsgbox0[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_rightmsgbox0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_rightmsgbox0[playerid], 1);

	td_p_rightmsgbox1[playerid] = CreatePlayerTextDraw(playerid, 588.666748, 124.792884, "tytul");
	PlayerTextDrawLetterSize(playerid, td_p_rightmsgbox1[playerid], 0.204844, 1.092266);
	PlayerTextDrawAlignment(playerid, td_p_rightmsgbox1[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_rightmsgbox1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_rightmsgbox1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_rightmsgbox1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_rightmsgbox1[playerid], -2147483393);
	PlayerTextDrawFont(playerid, td_p_rightmsgbox1[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_rightmsgbox1[playerid], 1);

	td_p_cargoinfo0[playerid] = CreatePlayerTextDraw(playerid, 310.443878, 1.393816, "Towar: ~y~Benzyna bezolowiowa");
	PlayerTextDrawLetterSize(playerid, td_p_cargoinfo0[playerid], 0.197777, 0.649244);
	PlayerTextDrawAlignment(playerid, td_p_cargoinfo0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_cargoinfo0[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_p_cargoinfo0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_cargoinfo0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_cargoinfo0[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_cargoinfo0[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_cargoinfo0[playerid], 1);
	
	td_p_cargoinfo1[playerid] = CreatePlayerTextDraw(playerid, 425.221771, 1.099579, "Ilosc: ~y~24 ~w~(t)");
	PlayerTextDrawLetterSize(playerid, td_p_cargoinfo1[playerid], 0.197777, 0.649244);
	PlayerTextDrawAlignment(playerid, td_p_cargoinfo1[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_cargoinfo1[playerid], 16777215);
	PlayerTextDrawSetShadow(playerid, td_p_cargoinfo1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_cargoinfo1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_cargoinfo1[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_cargoinfo1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_cargoinfo1[playerid], 1);
	
	td_p_cargoinfo2[playerid] = CreatePlayerTextDraw(playerid, 477.154998, 1.552025, "CEL: ~w~Las Venturas");
	PlayerTextDrawLetterSize(playerid, td_p_cargoinfo2[playerid], 0.197777, 0.649244);
	PlayerTextDrawAlignment(playerid, td_p_cargoinfo2[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_cargoinfo2[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_p_cargoinfo2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_cargoinfo2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_cargoinfo2[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_cargoinfo2[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_cargoinfo2[playerid], 1);
	
	td_p_cargoinfo3[playerid] = CreatePlayerTextDraw(playerid, 564.466430, 1.755583, "1000$ ~y~za ~w~kurs");
	PlayerTextDrawLetterSize(playerid, td_p_cargoinfo3[playerid], 0.197777, 0.649244);
	PlayerTextDrawAlignment(playerid, td_p_cargoinfo3[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_cargoinfo3[playerid], 16711935);
	PlayerTextDrawSetShadow(playerid, td_p_cargoinfo3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_cargoinfo3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_cargoinfo3[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_cargoinfo3[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_cargoinfo3[playerid], 1);


	td_p_trucksalon0[playerid] = CreatePlayerTextDraw(playerid, 194.355453, 325.048553, "Naczepa art.: Stale (small)");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon0[playerid], 0.364799, 1.104710);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_trucksalon0[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon0[playerid], -16777059);
	PlayerTextDrawFont(playerid, td_p_trucksalon0[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon0[playerid], 1);

	td_p_trucksalon1[playerid] = CreatePlayerTextDraw(playerid, 437.244354, 322.659637, "1000000 $");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon1[playerid], 0.412888, 1.579590);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon1[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon1[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon1[playerid], 16711935);
	PlayerTextDrawFont(playerid, td_p_trucksalon1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon1[playerid], 1);

	td_p_trucksalon2[playerid] = CreatePlayerTextDraw(playerid, 342.000091, 342.172424, "Dopuszczalna ladownosc: ~r~25000 ~w~[kg]");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon2[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon2[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon2[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon2[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon2[playerid], 1);

	td_p_trucksalon3[playerid] = CreatePlayerTextDraw(playerid, 342.022399, 352.132354, "Typ paliwa: ~y~ON");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon3[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon3[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon3[playerid], 1116715263);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon3[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon3[playerid], 1);

	td_p_trucksalon4[playerid] = CreatePlayerTextDraw(playerid, 341.644561, 361.494964, "Pojemnosc zbiornika: ~g~50 ~w~[litr]");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon4[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon4[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon4[playerid], 1841689599);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon4[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon4[playerid], 1);

	td_p_trucksalon5[playerid] = CreatePlayerTextDraw(playerid, 341.644470, 372.047912, "Spalanie: ~g~5.0 ~w~[litr/100]");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon5[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon5[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon5[playerid], 1116715263);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon5[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon5[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon5[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon5[playerid], 1);

	td_p_trucksalon6[playerid] = CreatePlayerTextDraw(playerid, 343.755767, 381.858520, "Przyspieszenie (0-100): ~g~3.6 ~w~[sekund]");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon6[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon6[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon6[playerid], 1841689599);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon6[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon6[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon6[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon6[playerid], 1);

	td_p_trucksalon7[playerid] = CreatePlayerTextDraw(playerid, 342.244384, 391.863891, "Predkosc maksymalna (V-MAX): ~g~100 ~w~[km/h]");
	PlayerTextDrawLetterSize(playerid, td_p_trucksalon7[playerid], 0.202933, 1.038009);
	PlayerTextDrawAlignment(playerid, td_p_trucksalon7[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_trucksalon7[playerid], 1116715263);
	PlayerTextDrawSetShadow(playerid, td_p_trucksalon7[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_trucksalon7[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_trucksalon7[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_trucksalon7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_trucksalon7[playerid], 1);

	td_p_confirmcargo1[playerid] = CreatePlayerTextDraw(playerid, 300.088867, 201.948562, "Nazwa towaru:~n~Ilosc:~n~Naczepa:~n~ADR:");
	PlayerTextDrawLetterSize(playerid, td_p_confirmcargo1[playerid], 0.170888, 0.944924);
	PlayerTextDrawAlignment(playerid, td_p_confirmcargo1[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_confirmcargo1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_confirmcargo1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_confirmcargo1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_confirmcargo1[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_confirmcargo1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_confirmcargo1[playerid], 1);

	td_p_confirmcargo2[playerid] = CreatePlayerTextDraw(playerid, 260.666625, 240.277420, "+10000$");
	PlayerTextDrawLetterSize(playerid, td_p_confirmcargo2[playerid], 0.449999, 1.600000);
	PlayerTextDrawAlignment(playerid, td_p_confirmcargo2[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_confirmcargo2[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_confirmcargo2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_confirmcargo2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_confirmcargo2[playerid], 16711935);
	PlayerTextDrawFont(playerid, td_p_confirmcargo2[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_confirmcargo2[playerid], 1);

	td_p_confirmcargo3[playerid] = CreatePlayerTextDraw(playerid, 260.777709, 255.712997, "+5 score");
	PlayerTextDrawLetterSize(playerid, td_p_confirmcargo3[playerid], 0.449999, 1.600000);
	PlayerTextDrawAlignment(playerid, td_p_confirmcargo3[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_confirmcargo3[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_confirmcargo3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_confirmcargo3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_confirmcargo3[playerid], -1);
	PlayerTextDrawFont(playerid, td_p_confirmcargo3[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_confirmcargo3[playerid], 1);

	td_p_confirmcargo4[playerid] = CreatePlayerTextDraw(playerid,202.000000, 179.000000, "trailermodel");
	PlayerTextDrawBackgroundColor(playerid,td_p_confirmcargo4[playerid], -255);
	PlayerTextDrawFont(playerid,td_p_confirmcargo4[playerid], 5);
	PlayerTextDrawLetterSize(playerid,td_p_confirmcargo4[playerid], 0.500000, 1.000000);
	PlayerTextDrawColor(playerid,td_p_confirmcargo4[playerid], -1);
	PlayerTextDrawSetOutline(playerid,td_p_confirmcargo4[playerid], 0);
	PlayerTextDrawSetProportional(playerid,td_p_confirmcargo4[playerid], 1);
	PlayerTextDrawSetShadow(playerid,td_p_confirmcargo4[playerid], 1);
	PlayerTextDrawUseBox(playerid,td_p_confirmcargo4[playerid], 1);
	PlayerTextDrawBoxColor(playerid,td_p_confirmcargo4[playerid], -255);
	PlayerTextDrawTextSize(playerid,td_p_confirmcargo4[playerid], 96.000000, 80.000000);
	PlayerTextDrawSetPreviewModel(playerid, td_p_confirmcargo4[playerid], 435);
	PlayerTextDrawSetPreviewRot(playerid, td_p_confirmcargo4[playerid], -30.000000, 0.000000, 50.000000, 1.100000);
	
	td_p_gpsdistance[playerid] = CreatePlayerTextDraw(playerid, 88.444358, 328.483856, "_");
	PlayerTextDrawLetterSize(playerid, td_p_gpsdistance[playerid], 0.216488, 1.043483);
	PlayerTextDrawAlignment(playerid, td_p_gpsdistance[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_gpsdistance[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_gpsdistance[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_gpsdistance[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_gpsdistance[playerid], -16776961);
	PlayerTextDrawFont(playerid, td_p_gpsdistance[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_gpsdistance[playerid], 1);

	td_p_delivered0[playerid] = CreatePlayerTextDraw(playerid, 217.650009, 210.641647, "] Dostarczenie ladunku~n~] Bezkolizyjna jazda~n~] Ostrozna jazda~n~] 1~n~] 2~n~] 3~n~] 4~n~] 5");
	PlayerTextDrawLetterSize(playerid, td_p_delivered0[playerid], 0.204299, 1.020166);
	PlayerTextDrawAlignment(playerid, td_p_delivered0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_delivered0[playerid], -5963521);
	PlayerTextDrawSetShadow(playerid, td_p_delivered0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_delivered0[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, td_p_delivered0[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_delivered0[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_delivered0[playerid], 1);

	td_p_delivered1[playerid] = CreatePlayerTextDraw(playerid, 416.399963, 210.358352, "~r~+~w~3000~g~$ ~w~~r~+~w~5~b~ score~n~");
	PlayerTextDrawLetterSize(playerid, td_p_delivered1[playerid], 0.204299, 1.020166);
	PlayerTextDrawAlignment(playerid, td_p_delivered1[playerid], 3);
	PlayerTextDrawColor(playerid, td_p_delivered1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_delivered1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_delivered1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, td_p_delivered1[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_delivered1[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_delivered1[playerid], 1);

	td_p_delivered2[playerid] = CreatePlayerTextDraw(playerid, 253.599929, 290.091705, "$7000");
	PlayerTextDrawLetterSize(playerid, td_p_delivered2[playerid], 0.320600, 1.237749);
	PlayerTextDrawAlignment(playerid, td_p_delivered2[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_delivered2[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_delivered2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_delivered2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_delivered2[playerid], 16711935);
	PlayerTextDrawFont(playerid, td_p_delivered2[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_delivered2[playerid], 1);

	td_p_delivered3[playerid] = CreatePlayerTextDraw(playerid, 368.849884, 290.683380, "+90");
	PlayerTextDrawLetterSize(playerid, td_p_delivered3[playerid], 0.320600, 1.237749);
	PlayerTextDrawAlignment(playerid, td_p_delivered3[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_delivered3[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_delivered3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_delivered3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_delivered3[playerid], -16776961);
	PlayerTextDrawFont(playerid, td_p_delivered3[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_delivered3[playerid], 1);

	anntd[playerid] = CreatePlayerTextDraw(playerid, 319.644409, 130.567321, "annuance");
	PlayerTextDrawLetterSize(playerid, anntd[playerid], 0.599511, 3.147590);
	PlayerTextDrawAlignment(playerid, anntd[playerid], 2);
	PlayerTextDrawColor(playerid, anntd[playerid], 255);
	PlayerTextDrawSetShadow(playerid, anntd[playerid], 0);
	PlayerTextDrawSetOutline(playerid, anntd[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, anntd[playerid], 16711935);
	PlayerTextDrawFont(playerid, anntd[playerid], 3);
	PlayerTextDrawSetProportional(playerid, anntd[playerid], 1);

	td_p_saction0[playerid] = CreatePlayerTextDraw(playerid, 567.688842, 136.142181, "Aby aktywowac ~r~brame~w~, wcisnij klawisz ~y~H~w~.");
	PlayerTextDrawLetterSize(playerid, td_p_saction0[playerid], 0.170666, 1.137564);
	PlayerTextDrawAlignment(playerid, td_p_saction0[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_saction0[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_saction0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_saction0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_saction0[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_saction0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_saction0[playerid], 1);

	ftool0[playerid] = CreatePlayerTextDraw(playerid, 310.799987, 349.141448, "~n~tresc");
	PlayerTextDrawLetterSize(playerid, ftool0[playerid], 0.166533, 0.961351);
	PlayerTextDrawTextSize(playerid, ftool0[playerid], 410.355468, 48.135112);
	PlayerTextDrawAlignment(playerid, ftool0[playerid], 1);
	PlayerTextDrawColor(playerid, ftool0[playerid], -1);
	PlayerTextDrawUseBox(playerid, ftool0[playerid], true);
	PlayerTextDrawBoxColor(playerid, ftool0[playerid], 102);
	PlayerTextDrawSetShadow(playerid, ftool0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, ftool0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, ftool0[playerid], 51);
	PlayerTextDrawFont(playerid, ftool0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, ftool0[playerid], 1);
	
	ftool1[playerid] = CreatePlayerTextDraw(playerid, 360.622222, 338.687927, "tytul");
	PlayerTextDrawLetterSize(playerid, ftool1[playerid], 0.231555, 1.457635);
	PlayerTextDrawAlignment(playerid, ftool1[playerid], 2);
	PlayerTextDrawColor(playerid, ftool1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, ftool1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, ftool1[playerid], 2);
	PlayerTextDrawBackgroundColor(playerid, ftool1[playerid], 255);
	PlayerTextDrawFont(playerid, ftool1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, ftool1[playerid], 1);

	td_p_fullscreen[playerid] = CreatePlayerTextDraw(playerid, 741.688720, -84.914222, "usebox");
	PlayerTextDrawLetterSize(playerid, td_p_fullscreen[playerid], 0.000000, 66.186042);
	PlayerTextDrawTextSize(playerid, td_p_fullscreen[playerid], -104.577789, 0.000000);
	PlayerTextDrawAlignment(playerid, td_p_fullscreen[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_fullscreen[playerid], 0);
	PlayerTextDrawUseBox(playerid, td_p_fullscreen[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_fullscreen[playerid], -208);
	PlayerTextDrawSetShadow(playerid, td_p_fullscreen[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_fullscreen[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_fullscreen[playerid], 0);

	td_p_taxi0[playerid] = CreatePlayerTextDraw(playerid, 233.866653, 351.381317, "Oplata za km: ~g~~h~~h~5$");
	PlayerTextDrawLetterSize(playerid, td_p_taxi0[playerid], 0.226844, 1.192320);
	PlayerTextDrawAlignment(playerid, td_p_taxi0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_taxi0[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_taxi0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_taxi0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_taxi0[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_taxi0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_taxi0[playerid], 1);

	td_p_taxi1[playerid] = CreatePlayerTextDraw(playerid, 234.555587, 362.983978, "Przebyty dystans: ~b~~h~~h~100 km");
	PlayerTextDrawLetterSize(playerid, td_p_taxi1[playerid], 0.226844, 1.192320);
	PlayerTextDrawAlignment(playerid, td_p_taxi1[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_taxi1[playerid], -1);
	PlayerTextDrawSetShadow(playerid, td_p_taxi1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_taxi1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_taxi1[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_taxi1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_taxi1[playerid], 1);

	td_p_taxi2[playerid] = CreatePlayerTextDraw(playerid, 317.644439, 388.714660, "5$");
	PlayerTextDrawLetterSize(playerid, td_p_taxi2[playerid], 0.449999, 1.600000);
	PlayerTextDrawAlignment(playerid, td_p_taxi2[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_taxi2[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_taxi2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_taxi2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_taxi2[playerid], 16711935);
	PlayerTextDrawFont(playerid, td_p_taxi2[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_taxi2[playerid], 1);

	td_p_dokument0[playerid] = CreatePlayerTextDraw(playerid, 278.577941, 209.315612, "Nick: ---~n~Wiek: ---~n~Plec: ---~n~Numer dokumentu: ---");
	PlayerTextDrawLetterSize(playerid, td_p_dokument0[playerid], 0.227555, 0.927004);
	PlayerTextDrawAlignment(playerid, td_p_dokument0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_dokument0[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_dokument0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dokument0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dokument0[playerid], -1);
	PlayerTextDrawFont(playerid, td_p_dokument0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_dokument0[playerid], 1);

	td_p_dokument1[playerid] = CreatePlayerTextDraw(playerid, 331.377899, 252.323577, "B,CE");
	PlayerTextDrawLetterSize(playerid, td_p_dokument1[playerid], 0.429553, 1.585065);
	PlayerTextDrawAlignment(playerid, td_p_dokument1[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_dokument1[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_dokument1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_dokument1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_dokument1[playerid], 8388863);
	PlayerTextDrawFont(playerid, td_p_dokument1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_dokument1[playerid], 1);

	td_p_dokument2[playerid] = CreatePlayerTextDraw(playerid,225.000000, 201.000000, "skindokument");
	PlayerTextDrawBackgroundColor(playerid,td_p_dokument2[playerid], -255);
	PlayerTextDrawFont(playerid,td_p_dokument2[playerid], 5);
	PlayerTextDrawLetterSize(playerid,td_p_dokument2[playerid], 0.500000, 1.000000);
	PlayerTextDrawColor(playerid,td_p_dokument2[playerid], -1);
	PlayerTextDrawSetOutline(playerid,td_p_dokument2[playerid], 0);
	PlayerTextDrawSetProportional(playerid,td_p_dokument2[playerid], 1);
	PlayerTextDrawSetShadow(playerid,td_p_dokument2[playerid], 1);
	PlayerTextDrawUseBox(playerid,td_p_dokument2[playerid], 1);
	PlayerTextDrawBoxColor(playerid,td_p_dokument2[playerid], -255);
	PlayerTextDrawTextSize(playerid,td_p_dokument2[playerid], 60.000000, 70.000000);
	PlayerTextDrawSetSelectable(playerid,td_p_dokument2[playerid], 0);

	td_p_adminspec0[playerid] = CreatePlayerTextDraw(playerid, 220.533294, 353.919952, "~n~Nick: sebaqq6 # Ping: 10 # Kasa: 100$ # Score: 30 # Frakcja: Policja # ~n~~r~~h~~h~Uzyj przyciskow myszy, aby zmienic gracza");
	PlayerTextDrawLetterSize(playerid, td_p_adminspec0[playerid], 0.198933, 1.116158);
	PlayerTextDrawTextSize(playerid, td_p_adminspec0[playerid], 420.222198, -18.467557);
	PlayerTextDrawAlignment(playerid, td_p_adminspec0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_adminspec0[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_p_adminspec0[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_adminspec0[playerid], -2139062176);
	PlayerTextDrawSetShadow(playerid, td_p_adminspec0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_adminspec0[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_adminspec0[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_adminspec0[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_adminspec0[playerid], 1);

	td_p_adminspec1[playerid] = CreatePlayerTextDraw(playerid, 269.911071, 345.009765, "DANE GRACZA");
	PlayerTextDrawLetterSize(playerid, td_p_adminspec1[playerid], 0.449999, 1.600000);
	PlayerTextDrawAlignment(playerid, td_p_adminspec1[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_adminspec1[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_adminspec1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_adminspec1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_adminspec1[playerid], -1);
	PlayerTextDrawFont(playerid, td_p_adminspec1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_adminspec1[playerid], 1);
	//printf("[DEBUG]TextDrawCount (per-player): %d", td_p_taxi2[playerid]);//ustawić ostatni TD

	tdCombine0[playerid] = CreatePlayerTextDraw(playerid, 439.000000, 317.812500, "boxaction");
	PlayerTextDrawLetterSize(playerid, tdCombine0[playerid], 0.000000, 7.154166);
	PlayerTextDrawTextSize(playerid, tdCombine0[playerid], 198.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, tdCombine0[playerid], 1);
	PlayerTextDrawColor(playerid, tdCombine0[playerid], 0);
	PlayerTextDrawUseBox(playerid, tdCombine0[playerid], true);
	PlayerTextDrawBoxColor(playerid, tdCombine0[playerid], 102);
	PlayerTextDrawSetShadow(playerid, tdCombine0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine0[playerid], 0);
	PlayerTextDrawFont(playerid, tdCombine0[playerid], 0);

	tdCombine1[playerid] = CreatePlayerTextDraw(playerid, 319.000000, 307.562500, "laweczka");
	PlayerTextDrawLetterSize(playerid, tdCombine1[playerid], 0.449999, 1.600000);
	PlayerTextDrawAlignment(playerid, tdCombine1[playerid], 2);
	PlayerTextDrawColor(playerid, tdCombine1[playerid], -2139062017);
	PlayerTextDrawSetShadow(playerid, tdCombine1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine1[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine1[playerid], 2);
	PlayerTextDrawSetProportional(playerid, tdCombine1[playerid], 1);

	tdCombine2[playerid] = CreatePlayerTextDraw(playerid, 317.000000, 372.750000, "((Wykonaj powyzsza kombinacje za pomoca strzalek na klawiaturze.))");
	PlayerTextDrawLetterSize(playerid, tdCombine2[playerid], 0.169500, 0.930625);
	PlayerTextDrawAlignment(playerid, tdCombine2[playerid], 2);
	PlayerTextDrawColor(playerid, tdCombine2[playerid], -2139062017);
	PlayerTextDrawSetShadow(playerid, tdCombine2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine2[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine2[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, tdCombine2[playerid], 1);

	tdCombine3[playerid] = CreatePlayerTextDraw(playerid, 202.500000, 322.437500, "Ilosc powtorzen: ~y~10");
	PlayerTextDrawLetterSize(playerid, tdCombine3[playerid], 0.218000, 0.970001);
	PlayerTextDrawAlignment(playerid, tdCombine3[playerid], 1);
	PlayerTextDrawColor(playerid, tdCombine3[playerid], -1);
	PlayerTextDrawSetShadow(playerid, tdCombine3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine3[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine3[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, tdCombine3[playerid], 1);

	tdCombine4[playerid] = CreatePlayerTextDraw(playerid, 433.000000, 323.000000, "Ilosc blednych kombinacji: ~g~0~w~/~r~3");
	PlayerTextDrawLetterSize(playerid, tdCombine4[playerid], 0.218000, 0.970001);
	PlayerTextDrawAlignment(playerid, tdCombine4[playerid], 3);
	PlayerTextDrawColor(playerid, tdCombine4[playerid], -1);
	PlayerTextDrawSetShadow(playerid, tdCombine4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine4[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, tdCombine4[playerid], 1);

	tdCombine5[playerid] = CreatePlayerTextDraw(playerid, 378.000000, 349.312500, "boxkombinacja");
	PlayerTextDrawLetterSize(playerid, tdCombine5[playerid], 0.000000, 1.768055);
	PlayerTextDrawTextSize(playerid, tdCombine5[playerid], 254.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, tdCombine5[playerid], 1);
	PlayerTextDrawColor(playerid, tdCombine5[playerid], 0);
	PlayerTextDrawUseBox(playerid, tdCombine5[playerid], true);
	PlayerTextDrawBoxColor(playerid, tdCombine5[playerid], 102);
	PlayerTextDrawSetShadow(playerid, tdCombine5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine5[playerid], 0);
	PlayerTextDrawFont(playerid, tdCombine5[playerid], 0);

	tdCombine6[playerid] = CreatePlayerTextDraw(playerid, 316.500000, 340.375000, "kombinacja");
	PlayerTextDrawLetterSize(playerid, tdCombine6[playerid], 0.212500, 0.755624);
	PlayerTextDrawAlignment(playerid, tdCombine6[playerid], 2);
	PlayerTextDrawColor(playerid, tdCombine6[playerid], -2139062017);
	PlayerTextDrawSetShadow(playerid, tdCombine6[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine6[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine6[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine6[playerid], 3);
	PlayerTextDrawSetProportional(playerid, tdCombine6[playerid], 1);

	tdCombine7[playerid] = CreatePlayerTextDraw(playerid, 258.500000, 348.250000, "~d~~u~~<~~>~~<~~u~");
	PlayerTextDrawLetterSize(playerid, tdCombine7[playerid], 0.769499, 1.687500);
	PlayerTextDrawAlignment(playerid, tdCombine7[playerid], 1);
	PlayerTextDrawColor(playerid, tdCombine7[playerid], -1);
	PlayerTextDrawSetShadow(playerid, tdCombine7[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine7[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine7[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine7[playerid], 1);
	PlayerTextDrawSetProportional(playerid, tdCombine7[playerid], 1);

	tdCombine8[playerid] = CreatePlayerTextDraw(playerid, 387.000000, 352.187500, "~g~0~w~/~r~6");
	PlayerTextDrawLetterSize(playerid, tdCombine8[playerid], 0.387500, 1.074999);
	PlayerTextDrawAlignment(playerid, tdCombine8[playerid], 1);
	PlayerTextDrawColor(playerid, tdCombine8[playerid], -1);
	PlayerTextDrawSetShadow(playerid, tdCombine8[playerid], 0);
	PlayerTextDrawSetOutline(playerid, tdCombine8[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, tdCombine8[playerid], 51);
	PlayerTextDrawFont(playerid, tdCombine8[playerid], 1);
	PlayerTextDrawSetProportional(playerid, tdCombine8[playerid], 1);

	td_p_pursuit0[playerid] = CreatePlayerTextDraw(playerid, 421.733245, 318.086669, "usebox");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit0[playerid], 0.000000, 7.426541);
	PlayerTextDrawTextSize(playerid, td_p_pursuit0[playerid], 207.066680, 0.000000);
	PlayerTextDrawAlignment(playerid, td_p_pursuit0[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit0[playerid], 0);
	PlayerTextDrawUseBox(playerid, td_p_pursuit0[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_pursuit0[playerid], 102);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit0[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit0[playerid], 0);
	
	td_p_pursuit1[playerid] = CreatePlayerTextDraw(playerid, 313.911193, 309.119903, "!!! POSCIG !!!");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit1[playerid], 0.485466, 1.604977);
	PlayerTextDrawAlignment(playerid, td_p_pursuit1[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_pursuit1[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit1[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit1[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_pursuit1[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_pursuit1[playerid], 3);
	PlayerTextDrawSetProportional(playerid, td_p_pursuit1[playerid], 1);
	
	td_p_pursuit2[playerid] = CreatePlayerTextDraw(playerid, 417.422241, 329.784423, "usebox");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit2[playerid], 0.000000, -0.334937);
	PlayerTextDrawTextSize(playerid, td_p_pursuit2[playerid], 211.377807, 0.000000);
	PlayerTextDrawAlignment(playerid, td_p_pursuit2[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit2[playerid], 65535);
	PlayerTextDrawUseBox(playerid, td_p_pursuit2[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_pursuit2[playerid], 65535);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit2[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit2[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit2[playerid], 0);
	
	td_p_pursuit3[playerid] = CreatePlayerTextDraw(playerid, 417.977661, 339.744415, "usebox");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit3[playerid], 0.000000, -0.334937);
	PlayerTextDrawTextSize(playerid, td_p_pursuit3[playerid], 210.933380, 0.000000);
	PlayerTextDrawAlignment(playerid, td_p_pursuit3[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit3[playerid], 65535);
	PlayerTextDrawUseBox(playerid, td_p_pursuit3[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_pursuit3[playerid], 65535);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit3[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit3[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit3[playerid], 1);
	
	td_p_pursuit4[playerid] = CreatePlayerTextDraw(playerid, 253.688873, 329.130676, "STATUS POSCIGU");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit4[playerid], 0.410488, 0.831928);
	PlayerTextDrawAlignment(playerid, td_p_pursuit4[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit4[playerid], 65535);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit4[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit4[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_pursuit4[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_pursuit4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_pursuit4[playerid], 1);
	
	td_p_pursuit5[playerid] = CreatePlayerTextDraw(playerid, 387.288848, 349.894592, "usebox");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit5[playerid], 0.000000, 2.150499);
	PlayerTextDrawTextSize(playerid, td_p_pursuit5[playerid], 242.800018, 0.000000);
	PlayerTextDrawAlignment(playerid, td_p_pursuit5[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit5[playerid], 0);
	PlayerTextDrawUseBox(playerid, td_p_pursuit5[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_pursuit5[playerid], 102);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit5[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit5[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit5[playerid], 0);
	
	td_p_pursuit6[playerid] = CreatePlayerTextDraw(playerid, 314.977569, 348.892639, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit6[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_p_pursuit6[playerid], -68.977706, 21.404445);
	PlayerTextDrawAlignment(playerid, td_p_pursuit6[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit6[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit6[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit6[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit6[playerid], 4);
	
	td_p_pursuit7[playerid] = CreatePlayerTextDraw(playerid, 315.488952, 348.892639, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit7[playerid], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_p_pursuit7[playerid], 68.755691, 21.404445);
	PlayerTextDrawAlignment(playerid, td_p_pursuit7[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit7[playerid], -2147483393);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit7[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit7[playerid], 0);
	PlayerTextDrawFont(playerid, td_p_pursuit7[playerid], 4);
	
	td_p_pursuit8[playerid] = CreatePlayerTextDraw(playerid, 211.733367, 346.801849, "UCIECZKA~n~- 1 score~n~- 6 ]]]");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit8[playerid], 0.148133, 0.867270);
	PlayerTextDrawAlignment(playerid, td_p_pursuit8[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit8[playerid], 8388863);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit8[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit8[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_pursuit8[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_pursuit8[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_pursuit8[playerid], 1);
	
	td_p_pursuit9[playerid] = CreatePlayerTextDraw(playerid, 386.955627, 348.299682, "ZLAPANY~n~30 min~n~wiezienia");
	PlayerTextDrawLetterSize(playerid, td_p_pursuit9[playerid], 0.148133, 0.867270);
	PlayerTextDrawAlignment(playerid, td_p_pursuit9[playerid], 1);
	PlayerTextDrawColor(playerid, td_p_pursuit9[playerid], -2147483393);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit9[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit9[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_pursuit9[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_pursuit9[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_pursuit9[playerid], 1);
	
	td_p_pursuit10[playerid] = CreatePlayerTextDraw(playerid, 317.466705, 371.889739, "_");//RADIOWOZ JEST ZBYT BLISKO!
	PlayerTextDrawLetterSize(playerid, td_p_pursuit10[playerid], 0.274888, 1.281422);
	PlayerTextDrawAlignment(playerid, td_p_pursuit10[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_pursuit10[playerid], -16776961);
	PlayerTextDrawSetShadow(playerid, td_p_pursuit10[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_pursuit10[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_pursuit10[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_pursuit10[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_pursuit10[playerid], 1);

	microactive[playerid] = CreatePlayerTextDraw(playerid, 417.000152, 81.375068, "Przechwytywanie");
	PlayerTextDrawLetterSize(playerid, microactive[playerid], 0.195399, 0.891686);
	PlayerTextDrawTextSize(playerid, microactive[playerid], 493.149841, -14.174994);
	PlayerTextDrawAlignment(playerid, microactive[playerid], 1);
	PlayerTextDrawColor(playerid, microactive[playerid], -16776961);
	PlayerTextDrawUseBox(playerid, microactive[playerid], true);
	PlayerTextDrawBoxColor(playerid, microactive[playerid], 36);
	PlayerTextDrawSetShadow(playerid, microactive[playerid], 0);
	PlayerTextDrawSetOutline(playerid, microactive[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, microactive[playerid], 255);
	PlayerTextDrawFont(playerid, microactive[playerid], 2);
	PlayerTextDrawSetProportional(playerid, microactive[playerid], 1);

	td_p_simpletext[playerid] = CreatePlayerTextDraw(playerid, 246.549743, 350.962402, "_");
	PlayerTextDrawLetterSize(playerid, td_p_simpletext[playerid], 0.216949, 1.132752);
	PlayerTextDrawTextSize(playerid, td_p_simpletext[playerid], 389.849822, 214.287445);
	PlayerTextDrawAlignment(playerid, td_p_simpletext[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_simpletext[playerid], -1);
	PlayerTextDrawUseBox(playerid, td_p_simpletext[playerid], true);
	PlayerTextDrawBoxColor(playerid, td_p_simpletext[playerid], 32);
	PlayerTextDrawSetShadow(playerid, td_p_simpletext[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_simpletext[playerid], 1);
	PlayerTextDrawBackgroundColor(playerid, td_p_simpletext[playerid], 255);
	PlayerTextDrawFont(playerid, td_p_simpletext[playerid], 1);
	PlayerTextDrawSetProportional(playerid, td_p_simpletext[playerid], 1);

	td_p_limit0[playerid] = CreatePlayerTextDraw(playerid, 476.444488-18.0, 27.875591, "120");
	PlayerTextDrawLetterSize(playerid, td_p_limit0[playerid], 0.273999, 1.191822);
	PlayerTextDrawAlignment(playerid, td_p_limit0[playerid], 2);
	PlayerTextDrawColor(playerid, td_p_limit0[playerid], 255);
	PlayerTextDrawSetShadow(playerid, td_p_limit0[playerid], 0);
	PlayerTextDrawSetOutline(playerid, td_p_limit0[playerid], 0);
	PlayerTextDrawBackgroundColor(playerid, td_p_limit0[playerid], 51);
	PlayerTextDrawFont(playerid, td_p_limit0[playerid], 2);
	PlayerTextDrawSetProportional(playerid, td_p_limit0[playerid], 1);

	vhl_playerlist[playerid] = CreatePlayerTextDraw(playerid, 634.300476, 126.218757, "[VHL]Lokalny~n~~w~player1");
	PlayerTextDrawLetterSize(playerid, vhl_playerlist[playerid], 0.196950, 0.832625);
	PlayerTextDrawAlignment(playerid, vhl_playerlist[playerid], 3);
	PlayerTextDrawColor(playerid, vhl_playerlist[playerid], 16711744);
	PlayerTextDrawSetShadow(playerid, vhl_playerlist[playerid], 0);
	PlayerTextDrawSetOutline(playerid, vhl_playerlist[playerid], 0);
	PlayerTextDrawFont(playerid, vhl_playerlist[playerid], 1);
	PlayerTextDrawSetProportional(playerid, vhl_playerlist[playerid], 1);

	return 1;
}

stock Init_TextDrawDynamic()
{
	/*panorama0 = TextDrawCreate(-57.333328, -22.400003, "LD_SPAC:white");
	TextDrawLetterSize(panorama0, 0.000000, 0.000000);
	TextDrawTextSize(panorama0, 719.111145, 126.933349);
	TextDrawAlignment(panorama0, 1);
	TextDrawColor(panorama0, 255);
	TextDrawSetShadow(panorama0, 0);
	TextDrawSetOutline(panorama0, 0);
	TextDrawFont(panorama0, 4);

	panorama1 = TextDrawCreate(-36.333305, 332.022186, "LD_SPAC:white");
	TextDrawLetterSize(panorama1, 0.000000, 0.000000);
	TextDrawTextSize(panorama1, 719.111145, 126.933349);
	TextDrawAlignment(panorama1, 1);
	TextDrawColor(panorama1, 255);
	TextDrawSetShadow(panorama1, 0);
	TextDrawSetOutline(panorama1, 0);
	TextDrawFont(panorama1, 4);*/
	panorama0 = TextDrawCreate(-2.950006, -0.874983, "mdl-2001:gradient_g");
	TextDrawLetterSize(panorama0, 0.000000, 0.000000);
	TextDrawTextSize(panorama0, 695.450256, 555.187561);
	TextDrawAlignment(panorama0, 1);
	TextDrawColor(panorama0, 255);
	TextDrawSetShadow(panorama0, 0);
	TextDrawSetOutline(panorama0, 0);
	TextDrawFont(panorama0, 4);
	
	panorama1 = TextDrawCreate(-16.950010, 2.399947, "mdl-2001:gradient_d");
	TextDrawLetterSize(panorama1, 0.000000, 0.000000);
	TextDrawTextSize(panorama1, 730.500549, 457.756347);
	TextDrawAlignment(panorama1, 1);
	TextDrawColor(panorama1, 255);
	TextDrawSetShadow(panorama1, 0);
	TextDrawSetOutline(panorama1, 0);
	TextDrawFont(panorama1, 4);

	logo_hl = TextDrawCreate(267.750183, 76.758308, "mdl-2001:logo_hl_2");
	TextDrawLetterSize(logo_hl, 0.000000, 0.000000);
	TextDrawTextSize(logo_hl, 106.033287, 119.284889);
	TextDrawAlignment(logo_hl, 1);
	TextDrawColor(logo_hl, -1);
	TextDrawSetShadow(logo_hl, 0);
	TextDrawSetOutline(logo_hl, 0);
	TextDrawFont(logo_hl, 4);


	td_radiocar11 = TextDrawCreate(506.222381, 381.795562+td_radiocar_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_radiocar11, 0.000000, 0.000000);
	TextDrawTextSize(td_radiocar11, 141.777770, 33.351112);
	TextDrawAlignment(td_radiocar11, 1);
	TextDrawColor(td_radiocar11, 255);
	TextDrawSetShadow(td_radiocar11, 0);
	TextDrawSetOutline(td_radiocar11, 0);
	TextDrawFont(td_radiocar11, 4);
	//Y: 412.662200
	td_radiocar12 = TextDrawCreate(505.889129, 413.662200+td_radiocar_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_radiocar12, 0.000000, 0.000000);
	TextDrawTextSize(td_radiocar12, 164.000015, 1.991103);
	TextDrawAlignment(td_radiocar12, 1);
	TextDrawColor(td_radiocar12, 808464639);
	TextDrawSetShadow(td_radiocar12, 0);
	TextDrawSetOutline(td_radiocar12, 0);
	TextDrawFont(td_radiocar12, 4);

	td_radiocar13 = TextDrawCreate(506.000061, 381.306854+td_radiocar_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_radiocar13, 0.000000, 0.000000);
	TextDrawTextSize(td_radiocar13, 164.000015, 1.991103);
	TextDrawAlignment(td_radiocar13, 1);
	TextDrawColor(td_radiocar13, 808464639);
	TextDrawSetShadow(td_radiocar13, 0);
	TextDrawSetOutline(td_radiocar13, 0);
	TextDrawFont(td_radiocar13, 4);

	td_radiocar14 = TextDrawCreate(574.666748, 383.786682+td_radiocar_offsetY, "Car Radio");
	TextDrawLetterSize(td_radiocar14, 0.191333, 0.664177);
	TextDrawAlignment(td_radiocar14, 1);
	TextDrawColor(td_radiocar14, -1);
	TextDrawSetShadow(td_radiocar14, 0);
	TextDrawSetOutline(td_radiocar14, 1);
	TextDrawBackgroundColor(td_radiocar14, 51);
	TextDrawFont(td_radiocar14, 1);
	TextDrawSetProportional(td_radiocar14, 1);

	td_G_carhud0 = TextDrawCreate(357.555664+td_carhud_offsetX, 342.477630+td_carhud_offsetY, "usebox");
	TextDrawLetterSize(td_G_carhud0, 0.000000, 8.532711);
	TextDrawTextSize(td_G_carhud0, 137.111160+td_carhud_offsetX, 0.000000);
	TextDrawAlignment(td_G_carhud0, 1);
	TextDrawColor(td_G_carhud0, 0);
	TextDrawUseBox(td_G_carhud0, true);
	TextDrawBoxColor(td_G_carhud0, 102);
	TextDrawSetShadow(td_G_carhud0, 0);
	TextDrawSetOutline(td_G_carhud0, 0);
	TextDrawFont(td_G_carhud0, 0);

	td_G_carhud1 = TextDrawCreate(142.666671+td_carhud_offsetX, 344.462219+td_carhud_offsetY, "LD_POOL:ball");
	TextDrawLetterSize(td_G_carhud1, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud1, 71.111114, 74.666671);
	TextDrawAlignment(td_G_carhud1, 1);
	TextDrawColor(td_G_carhud1, 269488383);
	TextDrawSetShadow(td_G_carhud1, 0);
	TextDrawSetOutline(td_G_carhud1, 0);
	TextDrawFont(td_G_carhud1, 4);

	td_G_carhud2 = TextDrawCreate(151.666671+td_carhud_offsetX, 353.127990+td_carhud_offsetY, "LD_POOL:ball");
	TextDrawLetterSize(td_G_carhud2, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud2, 53.777767, 57.244457);
	TextDrawAlignment(td_G_carhud2, 1);
	TextDrawColor(td_G_carhud2, 269488383);
	TextDrawSetShadow(td_G_carhud2, 0);
	TextDrawSetOutline(td_G_carhud2, 0);
	TextDrawFont(td_G_carhud2, 4);

	td_G_carhud3 = TextDrawCreate(222.222244+td_carhud_offsetX, 350.933288+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud3, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud3, 0.888899, 52.764450);
	TextDrawAlignment(td_G_carhud3, 1);
	TextDrawColor(td_G_carhud3, -1);
	TextDrawSetShadow(td_G_carhud3, 0);
	TextDrawSetOutline(td_G_carhud3, 0);
	TextDrawFont(td_G_carhud3, 4);

	td_G_carhud4 = TextDrawCreate(226.333343+td_carhud_offsetX, 350.788421+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud4, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud4, 0.888899, 52.764450);
	TextDrawAlignment(td_G_carhud4, 1);
	TextDrawColor(td_G_carhud4, -1);
	TextDrawSetShadow(td_G_carhud4, 0);
	TextDrawSetOutline(td_G_carhud4, 0);
	TextDrawFont(td_G_carhud4, 4);

	td_G_carhud5 = TextDrawCreate(219.777801+td_carhud_offsetX, 403.059417+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud5, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud5, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud5, 1);
	TextDrawColor(td_G_carhud5, -1);
	TextDrawSetShadow(td_G_carhud5, 0);
	TextDrawSetOutline(td_G_carhud5, 0);
	TextDrawFont(td_G_carhud5, 4);
	//TextDrawSetSelectable(td_G_carhud5, true);

	td_G_carhud6 = TextDrawCreate(219.711135+td_carhud_offsetX, 376.681701+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud6, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud6, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud6, 1);
	TextDrawColor(td_G_carhud6, -1);
	TextDrawSetShadow(td_G_carhud6, 0);
	TextDrawSetOutline(td_G_carhud6, 0);
	TextDrawFont(td_G_carhud6, 4);
	//TextDrawSetSelectable(td_G_carhud6, true);

	td_G_carhud7 = TextDrawCreate(219.822250+td_carhud_offsetX, 350.851440+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud7, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud7, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud7, 1);
	TextDrawColor(td_G_carhud7, -1);
	TextDrawSetShadow(td_G_carhud7, 0);
	TextDrawSetOutline(td_G_carhud7, 0);
	TextDrawFont(td_G_carhud7, 4);
	//TextDrawSetSelectable(td_G_carhud7, true);

	td_G_carhud8 = TextDrawCreate(230.666641+td_carhud_offsetX, 346.453399+td_carhud_offsetY, "F");
	TextDrawLetterSize(td_G_carhud8, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud8, 1);
	TextDrawColor(td_G_carhud8, -1);
	TextDrawSetShadow(td_G_carhud8, 0);
	TextDrawSetOutline(td_G_carhud8, 1);
	TextDrawBackgroundColor(td_G_carhud8, 51);
	TextDrawFont(td_G_carhud8, 2);
	TextDrawSetProportional(td_G_carhud8, 1);

	td_G_carhud9 = TextDrawCreate(230.777740+td_carhud_offsetX, 372.342315+td_carhud_offsetY, "1/2");
	TextDrawLetterSize(td_G_carhud9, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud9, 1);
	TextDrawColor(td_G_carhud9, -1);
	TextDrawSetShadow(td_G_carhud9, 0);
	TextDrawSetOutline(td_G_carhud9, 1);
	TextDrawBackgroundColor(td_G_carhud9, 51);
	TextDrawFont(td_G_carhud9, 2);
	TextDrawSetProportional(td_G_carhud9, 1);

	td_G_carhud10 = TextDrawCreate(230.755493+td_carhud_offsetX, 398.629455+td_carhud_offsetY, "E");
	TextDrawLetterSize(td_G_carhud10, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud10, 1);
	TextDrawColor(td_G_carhud10, -1);
	TextDrawSetShadow(td_G_carhud10, 0);
	TextDrawSetOutline(td_G_carhud10, 1);
	TextDrawBackgroundColor(td_G_carhud10, 51);
	TextDrawFont(td_G_carhud10, 2);
	TextDrawSetProportional(td_G_carhud10, 1);

	td_G_carhud11 = TextDrawCreate(334.733184+td_carhud_offsetX, 351.286132+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud11, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud11, 0.888899, 52.764450);
	TextDrawAlignment(td_G_carhud11, 1);
	TextDrawColor(td_G_carhud11, -1);
	TextDrawSetShadow(td_G_carhud11, 0);
	TextDrawSetOutline(td_G_carhud11, 0);
	TextDrawFont(td_G_carhud11, 4);

	td_G_carhud12 = TextDrawCreate(329.955291+td_carhud_offsetX, 351.390045+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud12, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud12, 0.888899, 52.764450);
	TextDrawAlignment(td_G_carhud12, 1);
	TextDrawColor(td_G_carhud12, -1);
	TextDrawSetShadow(td_G_carhud12, 0);
	TextDrawSetOutline(td_G_carhud12, 0);
	TextDrawFont(td_G_carhud12, 4);

	td_G_carhud13 = TextDrawCreate(328.022155+td_carhud_offsetX, 403.362579+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud13, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud13, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud13, 1);
	TextDrawColor(td_G_carhud13, -1);
	TextDrawSetShadow(td_G_carhud13, 0);
	TextDrawSetOutline(td_G_carhud13, 0);
	TextDrawFont(td_G_carhud13, 4);
	//TextDrawSetSelectable(td_G_carhud13, true);

	td_G_carhud14 = TextDrawCreate(328.088745+td_carhud_offsetX, 376.586547+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud14, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud14, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud14, 1);
	TextDrawColor(td_G_carhud14, -1);
	TextDrawSetShadow(td_G_carhud14, 0);
	TextDrawSetOutline(td_G_carhud14, 0);
	TextDrawFont(td_G_carhud14, 4);
	//TextDrawSetSelectable(td_G_carhud14, true);

	td_G_carhud15 = TextDrawCreate(328.199859+td_carhud_offsetX, 351.204376+td_carhud_offsetY, "LD_SPAC:white");
	TextDrawLetterSize(td_G_carhud15, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud15, 9.688899, 0.846225);
	TextDrawAlignment(td_G_carhud15, 1);
	TextDrawColor(td_G_carhud15, -1);
	TextDrawSetShadow(td_G_carhud15, 0);
	TextDrawSetOutline(td_G_carhud15, 0);
	TextDrawFont(td_G_carhud15, 4);
	//TextDrawSetSelectable(td_G_carhud15, true);

	td_G_carhud16 = TextDrawCreate(339.133239+td_carhud_offsetX, 346.905853+td_carhud_offsetY, "110");
	TextDrawLetterSize(td_G_carhud16, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud16, 1);
	TextDrawColor(td_G_carhud16, -1);
	TextDrawSetShadow(td_G_carhud16, 0);
	TextDrawSetOutline(td_G_carhud16, 1);
	TextDrawBackgroundColor(td_G_carhud16, 51);
	TextDrawFont(td_G_carhud16, 2);
	TextDrawSetProportional(td_G_carhud16, 1);

	td_G_carhud17 = TextDrawCreate(338.577636+td_carhud_offsetX, 371.998321+td_carhud_offsetY, "90");
	TextDrawLetterSize(td_G_carhud17, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud17, 1);
	TextDrawColor(td_G_carhud17, -1);
	TextDrawSetShadow(td_G_carhud17, 0);
	TextDrawSetOutline(td_G_carhud17, 1);
	TextDrawBackgroundColor(td_G_carhud17, 51);
	TextDrawFont(td_G_carhud17, 2);
	TextDrawSetProportional(td_G_carhud17, 1);

	td_G_carhud18 = TextDrawCreate(338.199920+td_carhud_offsetX, 398.733337+td_carhud_offsetY, "70");
	TextDrawLetterSize(td_G_carhud18, 0.141377, 0.919039);
	TextDrawAlignment(td_G_carhud18, 1);
	TextDrawColor(td_G_carhud18, -1);
	TextDrawSetShadow(td_G_carhud18, 0);
	TextDrawSetOutline(td_G_carhud18, 1);
	TextDrawBackgroundColor(td_G_carhud18, 51);
	TextDrawFont(td_G_carhud18, 2);
	TextDrawSetProportional(td_G_carhud18, 1);

	td_G_carhud19 = TextDrawCreate(348.533294+td_carhud_offsetX, 344.860473+td_carhud_offsetY, "o");
	TextDrawLetterSize(td_G_carhud19, 0.172533, 0.655713);
	TextDrawAlignment(td_G_carhud19, 1);
	TextDrawColor(td_G_carhud19, -1);
	TextDrawSetShadow(td_G_carhud19, 0);
	TextDrawSetOutline(td_G_carhud19, 1);
	TextDrawBackgroundColor(td_G_carhud19, 51);
	TextDrawFont(td_G_carhud19, 1);
	TextDrawSetProportional(td_G_carhud19, 1);

	td_G_carhud20 = TextDrawCreate(346.911102+td_carhud_offsetX, 370.151916+td_carhud_offsetY, "o");
	TextDrawLetterSize(td_G_carhud20, 0.172533, 0.655713);
	TextDrawAlignment(td_G_carhud20, 1);
	TextDrawColor(td_G_carhud20, -1);
	TextDrawSetShadow(td_G_carhud20, 0);
	TextDrawSetOutline(td_G_carhud20, 1);
	TextDrawBackgroundColor(td_G_carhud20, 51);
	TextDrawFont(td_G_carhud20, 1);
	TextDrawSetProportional(td_G_carhud20, 1);

	td_G_carhud21 = TextDrawCreate(346.088867+td_carhud_offsetX, 396.986511+td_carhud_offsetY, "o");
	TextDrawLetterSize(td_G_carhud21, 0.172533, 0.655713);
	TextDrawAlignment(td_G_carhud21, 1);
	TextDrawColor(td_G_carhud21, -1);
	TextDrawSetShadow(td_G_carhud21, 0);
	TextDrawSetOutline(td_G_carhud21, 1);
	TextDrawBackgroundColor(td_G_carhud21, 51);
	TextDrawFont(td_G_carhud21, 1);
	TextDrawSetProportional(td_G_carhud21, 1);

	td_G_carhud22 = TextDrawCreate(274.844329+td_carhud_offsetX, 368.903137+td_carhud_offsetY, "hud:radar_gangY");
	TextDrawLetterSize(td_G_carhud22, 0.000000, 0.000000);
	TextDrawTextSize(td_G_carhud22, 14.088884, 10.304010);
	TextDrawAlignment(td_G_carhud22, 1);
	TextDrawColor(td_G_carhud22, -99);
	TextDrawSetShadow(td_G_carhud22, 0);
	TextDrawSetOutline(td_G_carhud22, 0);
	TextDrawFont(td_G_carhud22, 4);

	td_G_carhud23 = TextDrawCreate(274.822052+td_carhud_offsetX, 369.006896+td_carhud_offsetY, "/");
	TextDrawLetterSize(td_G_carhud23, 0.891155, 1.113173);
	TextDrawAlignment(td_G_carhud23, 1);
	TextDrawColor(td_G_carhud23, 0x000000FF);//-77397761
	TextDrawSetShadow(td_G_carhud23, 0);
	TextDrawSetOutline(td_G_carhud23, 0);
	TextDrawBackgroundColor(td_G_carhud23, 51);
	TextDrawFont(td_G_carhud23, 2);
	TextDrawSetProportional(td_G_carhud23, 1);

	td_G_carhud24 = TextDrawCreate(270.399810+td_carhud_offsetX, 344.014282+td_carhud_offsetY, "ZAMKNIETY");
	TextDrawLetterSize(td_G_carhud24, 0.127733, 0.578558);
	TextDrawAlignment(td_G_carhud24, 1);
	TextDrawColor(td_G_carhud24, -16776961);
	TextDrawSetShadow(td_G_carhud24, 0);
	TextDrawSetOutline(td_G_carhud24, 0);
	TextDrawBackgroundColor(td_G_carhud24, 51);
	TextDrawFont(td_G_carhud24, 1);
	TextDrawSetProportional(td_G_carhud24, 1);

	td_g_dystrybutor0 = TextDrawCreate(260.755767, 302.001831, "ld_pool:ball");
	TextDrawLetterSize(td_g_dystrybutor0, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor0, 18.799995, 18.268438);
	TextDrawAlignment(td_g_dystrybutor0, 1);
	TextDrawColor(td_g_dystrybutor0, 255);
	TextDrawSetShadow(td_g_dystrybutor0, 0);
	TextDrawSetOutline(td_g_dystrybutor0, 0);
	TextDrawFont(td_g_dystrybutor0, 4);

	td_g_dystrybutor1 = TextDrawCreate(350.911193, 302.006317, "ld_pool:ball");
	TextDrawLetterSize(td_g_dystrybutor1, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor1, 18.799995, 18.268438);
	TextDrawAlignment(td_g_dystrybutor1, 1);
	TextDrawColor(td_g_dystrybutor1, 255);
	TextDrawSetShadow(td_g_dystrybutor1, 0);
	TextDrawSetOutline(td_g_dystrybutor1, 0);
	TextDrawFont(td_g_dystrybutor1, 4);

	td_g_dystrybutor2 = TextDrawCreate(267.288696, 210.759414, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor2, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor2, 95.022239, 109.162658);
	TextDrawAlignment(td_g_dystrybutor2, 1);
	TextDrawColor(td_g_dystrybutor2, 255);
	TextDrawSetShadow(td_g_dystrybutor2, 0);
	TextDrawSetOutline(td_g_dystrybutor2, 0);
	TextDrawFont(td_g_dystrybutor2, 4);

	td_g_dystrybutor3 = TextDrawCreate(253.177566, 149.338104, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor3, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor3, 123.422233, 62.720005);
	TextDrawAlignment(td_g_dystrybutor3, 1);
	TextDrawColor(td_g_dystrybutor3, 255);
	TextDrawSetShadow(td_g_dystrybutor3, 0);
	TextDrawSetOutline(td_g_dystrybutor3, 0);
	TextDrawFont(td_g_dystrybutor3, 4);

	td_g_dystrybutor4 = TextDrawCreate(296.044586, 156.700241, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor4, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor4, 36.933361, 12.543995);
	TextDrawAlignment(td_g_dystrybutor4, 1);
	TextDrawColor(td_g_dystrybutor4, -2139094785);
	TextDrawSetShadow(td_g_dystrybutor4, 0);
	TextDrawSetOutline(td_g_dystrybutor4, 0);
	TextDrawFont(td_g_dystrybutor4, 4);

	td_g_dystrybutor5 = TextDrawCreate(296.155700, 170.891387, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor5, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor5, 36.933361, 12.543995);
	TextDrawAlignment(td_g_dystrybutor5, 1);
	TextDrawColor(td_g_dystrybutor5, -2139094785);
	TextDrawSetShadow(td_g_dystrybutor5, 0);
	TextDrawSetOutline(td_g_dystrybutor5, 0);
	TextDrawFont(td_g_dystrybutor5, 4);

	td_g_dystrybutor6 = TextDrawCreate(296.088989, 185.281631, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor6, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor6, 36.933361, 12.543995);
	TextDrawAlignment(td_g_dystrybutor6, 1);
	TextDrawColor(td_g_dystrybutor6, -2139094785);
	TextDrawSetShadow(td_g_dystrybutor6, 0);
	TextDrawSetOutline(td_g_dystrybutor6, 0);
	TextDrawFont(td_g_dystrybutor6, 4);

	td_g_dystrybutor7 = TextDrawCreate(333.955566, 158.003555, "$");
	TextDrawLetterSize(td_g_dystrybutor7, 0.218933, 0.896640);
	TextDrawAlignment(td_g_dystrybutor7, 1);
	TextDrawColor(td_g_dystrybutor7, -1);
	TextDrawSetShadow(td_g_dystrybutor7, 0);
	TextDrawSetOutline(td_g_dystrybutor7, 1);
	TextDrawBackgroundColor(td_g_dystrybutor7, 51);
	TextDrawFont(td_g_dystrybutor7, 1);
	TextDrawSetProportional(td_g_dystrybutor7, 1);

	td_g_dystrybutor8 = TextDrawCreate(334.266723, 172.986663, "dm");
	TextDrawLetterSize(td_g_dystrybutor8, 0.218933, 0.896640);
	TextDrawAlignment(td_g_dystrybutor8, 1);
	TextDrawColor(td_g_dystrybutor8, -1);
	TextDrawSetShadow(td_g_dystrybutor8, 0);
	TextDrawSetOutline(td_g_dystrybutor8, 1);
	TextDrawBackgroundColor(td_g_dystrybutor8, 51);
	TextDrawFont(td_g_dystrybutor8, 1);
	TextDrawSetProportional(td_g_dystrybutor8, 1);

	td_g_dystrybutor9 = TextDrawCreate(346.311096, 170.945739, "3");
	TextDrawLetterSize(td_g_dystrybutor9, 0.234444, 0.852833);
	TextDrawAlignment(td_g_dystrybutor9, 1);
	TextDrawColor(td_g_dystrybutor9, -1);
	TextDrawSetShadow(td_g_dystrybutor9, 0);
	TextDrawSetOutline(td_g_dystrybutor9, 1);
	TextDrawBackgroundColor(td_g_dystrybutor9, 51);
	TextDrawFont(td_g_dystrybutor9, 1);
	TextDrawSetProportional(td_g_dystrybutor9, 1);

	td_g_dystrybutor10 = TextDrawCreate(334.111145, 186.969772, "$/dm");
	TextDrawLetterSize(td_g_dystrybutor10, 0.218933, 0.896640);
	TextDrawAlignment(td_g_dystrybutor10, 1);
	TextDrawColor(td_g_dystrybutor10, -1);
	TextDrawSetShadow(td_g_dystrybutor10, 0);
	TextDrawSetOutline(td_g_dystrybutor10, 1);
	TextDrawBackgroundColor(td_g_dystrybutor10, 51);
	TextDrawFont(td_g_dystrybutor10, 1);
	TextDrawSetProportional(td_g_dystrybutor10, 1);

	td_g_dystrybutor11 = TextDrawCreate(353.488861, 184.887908, "3");
	TextDrawLetterSize(td_g_dystrybutor11, 0.234444, 0.852833);
	TextDrawAlignment(td_g_dystrybutor11, 1);
	TextDrawColor(td_g_dystrybutor11, -1);
	TextDrawSetShadow(td_g_dystrybutor11, 0);
	TextDrawSetOutline(td_g_dystrybutor11, 1);
	TextDrawBackgroundColor(td_g_dystrybutor11, 51);
	TextDrawFont(td_g_dystrybutor11, 1);
	TextDrawSetProportional(td_g_dystrybutor11, 1);

	td_g_dystrybutor12 = TextDrawCreate(305.155548, 222.855087, "LD_SPAC:white");
	TextDrawLetterSize(td_g_dystrybutor12, 0.000000, 0.000000);
	TextDrawTextSize(td_g_dystrybutor12, 23.644453, 23.096900);
	TextDrawAlignment(td_g_dystrybutor12, 1);
	TextDrawColor(td_g_dystrybutor12, -1);
	TextDrawSetShadow(td_g_dystrybutor12, 0);
	TextDrawSetOutline(td_g_dystrybutor12, 0);
	TextDrawFont(td_g_dystrybutor12, 4);

	td_g_dystrybutor13 = TextDrawCreate(274.711090, 200.753784, "SAMOOBSLUGA");
	TextDrawLetterSize(td_g_dystrybutor13, 0.316843, 1.033527);
	TextDrawAlignment(td_g_dystrybutor13, 1);
	TextDrawColor(td_g_dystrybutor13, -1061109505);
	TextDrawSetShadow(td_g_dystrybutor13, 0);
	TextDrawSetOutline(td_g_dystrybutor13, 1);
	TextDrawBackgroundColor(td_g_dystrybutor13, 51);
	TextDrawFont(td_g_dystrybutor13, 1);
	TextDrawSetProportional(td_g_dystrybutor13, 1);

	td_g_dystrybutor14 = TextDrawCreate(257.288940, 145.848861, "1");
	TextDrawLetterSize(td_g_dystrybutor14, 0.612711, 4.134185);
	TextDrawAlignment(td_g_dystrybutor14, 1);
	TextDrawColor(td_g_dystrybutor14, -2139062017);
	TextDrawSetShadow(td_g_dystrybutor14, 0);
	TextDrawSetOutline(td_g_dystrybutor14, 1);
	TextDrawBackgroundColor(td_g_dystrybutor14, 51);
	TextDrawFont(td_g_dystrybutor14, 3);
	TextDrawSetProportional(td_g_dystrybutor14, 1);

	td_g_dystrybutor15 = TextDrawCreate(355.688812, 214.144073, ")");
	TextDrawLetterSize(td_g_dystrybutor15, 1.528399, 7.942187);
	TextDrawAlignment(td_g_dystrybutor15, 1);
	TextDrawColor(td_g_dystrybutor15, 255);
	TextDrawSetShadow(td_g_dystrybutor15, 0);
	TextDrawSetOutline(td_g_dystrybutor15, 1);
	TextDrawBackgroundColor(td_g_dystrybutor15, 51);
	TextDrawFont(td_g_dystrybutor15, 1);
	TextDrawSetProportional(td_g_dystrybutor15, 1);

	td_g_dystrybutor16 = TextDrawCreate(347.599792, 292.600402, "usebox");
	TextDrawLetterSize(td_g_dystrybutor16, 0.000000, -0.399627);
	TextDrawTextSize(td_g_dystrybutor16, 284.666473, 0.000000);
	TextDrawAlignment(td_g_dystrybutor16, 1);
	TextDrawColor(td_g_dystrybutor16, 0);
	TextDrawUseBox(td_g_dystrybutor16, true);
	TextDrawBoxColor(td_g_dystrybutor16, -1);
	TextDrawSetShadow(td_g_dystrybutor16, 0);
	TextDrawSetOutline(td_g_dystrybutor16, 0);
	TextDrawFont(td_g_dystrybutor16, 0);

	td_g_dystrybutor17 = TextDrawCreate(348.377593, 293.998596, "usebox");
	TextDrawLetterSize(td_g_dystrybutor17, 0.000000, -0.399627);
	TextDrawTextSize(td_g_dystrybutor17, 284.444274, 0.000000);
	TextDrawAlignment(td_g_dystrybutor17, 1);
	TextDrawColor(td_g_dystrybutor17, 0);
	TextDrawUseBox(td_g_dystrybutor17, true);
	TextDrawBoxColor(td_g_dystrybutor17, -1);
	TextDrawSetShadow(td_g_dystrybutor17, 0);
	TextDrawSetOutline(td_g_dystrybutor17, 0);
	TextDrawFont(td_g_dystrybutor17, 0);

	td_g_dystrybutor18 = TextDrawCreate(348.799835, 295.446563, "usebox");
	TextDrawLetterSize(td_g_dystrybutor18, 0.000000, -0.399627);
	TextDrawTextSize(td_g_dystrybutor18, 283.866516, 0.000000);
	TextDrawAlignment(td_g_dystrybutor18, 1);
	TextDrawColor(td_g_dystrybutor18, 0);
	TextDrawUseBox(td_g_dystrybutor18, true);
	TextDrawBoxColor(td_g_dystrybutor18, -1);
	TextDrawSetShadow(td_g_dystrybutor18, 0);
	TextDrawSetOutline(td_g_dystrybutor18, 0);
	TextDrawFont(td_g_dystrybutor18, 0);

	td_g_dystrybutor19 = TextDrawCreate(349.133209, 297.143432, "usebox");
	TextDrawLetterSize(td_g_dystrybutor19, 0.000000, -0.399627);
	TextDrawTextSize(td_g_dystrybutor19, 283.199890, 0.000000);
	TextDrawAlignment(td_g_dystrybutor19, 1);
	TextDrawColor(td_g_dystrybutor19, 0);
	TextDrawUseBox(td_g_dystrybutor19, true);
	TextDrawBoxColor(td_g_dystrybutor19, -1);
	TextDrawSetShadow(td_g_dystrybutor19, 0);
	TextDrawSetOutline(td_g_dystrybutor19, 0);
	TextDrawFont(td_g_dystrybutor19, 0);

	td_g_dystrybutor20 = TextDrawCreate(349.644348, 298.442108, "usebox");
	TextDrawLetterSize(td_g_dystrybutor20, 0.000000, -0.399627);
	TextDrawTextSize(td_g_dystrybutor20, 282.711029, 0.000000);
	TextDrawAlignment(td_g_dystrybutor20, 1);
	TextDrawColor(td_g_dystrybutor20, 0);
	TextDrawUseBox(td_g_dystrybutor20, true);
	TextDrawBoxColor(td_g_dystrybutor20, -1);
	TextDrawSetShadow(td_g_dystrybutor20, 0);
	TextDrawSetOutline(td_g_dystrybutor20, 0);
	TextDrawFont(td_g_dystrybutor20, 0);

	td_g_rightmsgbox0 = TextDrawCreate(638.266601, 126.840431, "usebox");
	TextDrawLetterSize(td_g_rightmsgbox0, 0.000000, 0.788024);
	TextDrawTextSize(td_g_rightmsgbox0, 534.710937, 0.000000);
	TextDrawAlignment(td_g_rightmsgbox0, 1);
	TextDrawColor(td_g_rightmsgbox0, 0);
	TextDrawUseBox(td_g_rightmsgbox0, true);
	TextDrawBoxColor(td_g_rightmsgbox0, 102);
	TextDrawSetShadow(td_g_rightmsgbox0, 0);
	TextDrawSetOutline(td_g_rightmsgbox0, 0);
	TextDrawFont(td_g_rightmsgbox0, 0);

	td_g_cargoinfo0 = TextDrawCreate(761.599853, -10.795109, "usebox");
	TextDrawLetterSize(td_g_cargoinfo0, 0.000000, 2.060616);
	TextDrawTextSize(td_g_cargoinfo0, 306.044616, 0.000000);
	TextDrawAlignment(td_g_cargoinfo0, 1);
	TextDrawColor(td_g_cargoinfo0, 0);
	TextDrawUseBox(td_g_cargoinfo0, true);
	TextDrawBoxColor(td_g_cargoinfo0, 102);
	TextDrawSetShadow(td_g_cargoinfo0, 0);
	TextDrawSetOutline(td_g_cargoinfo0, 0);
	TextDrawFont(td_g_cargoinfo0, 0);

	td_g_cargoinfo1 = TextDrawCreate(307.466674, 9.308427, "LD_SPAC:white");
	TextDrawLetterSize(td_g_cargoinfo1, 0.000000, 0.000000);
	TextDrawTextSize(td_g_cargoinfo1, 340.266693, 0.895987);
	TextDrawAlignment(td_g_cargoinfo1, 1);
	TextDrawColor(td_g_cargoinfo1, 65535);
	TextDrawSetShadow(td_g_cargoinfo1, 0);
	TextDrawSetOutline(td_g_cargoinfo1, 0);
	TextDrawFont(td_g_cargoinfo1, 4);

	td_g_cargoinfo2 = TextDrawCreate(307.266876, -19.956474, "LD_SPAC:white");
	TextDrawLetterSize(td_g_cargoinfo2, 0.000000, 0.000000);
	TextDrawTextSize(td_g_cargoinfo2, 1.022291, 29.269325);
	TextDrawAlignment(td_g_cargoinfo2, 1);
	TextDrawColor(td_g_cargoinfo2, 65535);
	TextDrawSetShadow(td_g_cargoinfo2, 0);
	TextDrawSetOutline(td_g_cargoinfo2, 0);
	TextDrawFont(td_g_cargoinfo2, 4);

	td_g_cargoinfo3 = TextDrawCreate(421.422271, -20.350244, "LD_SPAC:white");
	TextDrawLetterSize(td_g_cargoinfo3, 0.000000, 0.000000);
	TextDrawTextSize(td_g_cargoinfo3, 1.022291, 29.269325);
	TextDrawAlignment(td_g_cargoinfo3, 1);
	TextDrawColor(td_g_cargoinfo3, 65535);
	TextDrawSetShadow(td_g_cargoinfo3, 0);
	TextDrawSetOutline(td_g_cargoinfo3, 0);
	TextDrawFont(td_g_cargoinfo3, 4);

	td_g_cargoinfo4 = TextDrawCreate(473.533386, -20.495141, "LD_SPAC:white");
	TextDrawLetterSize(td_g_cargoinfo4, 0.000000, 0.000000);
	TextDrawTextSize(td_g_cargoinfo4, 1.022291, 29.269325);
	TextDrawAlignment(td_g_cargoinfo4, 1);
	TextDrawColor(td_g_cargoinfo4, 65535);
	TextDrawSetShadow(td_g_cargoinfo4, 0);
	TextDrawSetOutline(td_g_cargoinfo4, 0);
	TextDrawFont(td_g_cargoinfo4, 4);

	td_g_cargoinfo5 = TextDrawCreate(561.599975, -19.096920, "LD_SPAC:white");
	TextDrawLetterSize(td_g_cargoinfo5, 0.000000, 0.000000);
	TextDrawTextSize(td_g_cargoinfo5, 1.022291, 29.269325);
	TextDrawAlignment(td_g_cargoinfo5, 1);
	TextDrawColor(td_g_cargoinfo5, 65535);
	TextDrawSetShadow(td_g_cargoinfo5, 0);
	TextDrawSetOutline(td_g_cargoinfo5, 0);
	TextDrawFont(td_g_cargoinfo5, 4);

	td_g_trucksalon0 = TextDrawCreate(487.955780, 323.860778, "usebox");
	TextDrawLetterSize(td_g_trucksalon0, 0.000000, 10.037902);
	TextDrawTextSize(td_g_trucksalon0, 186.888916, 0.000000);
	TextDrawAlignment(td_g_trucksalon0, 1);
	TextDrawColor(td_g_trucksalon0, 0);
	TextDrawUseBox(td_g_trucksalon0, true);
	TextDrawBoxColor(td_g_trucksalon0, 102);
	TextDrawSetShadow(td_g_trucksalon0, 0);
	TextDrawSetOutline(td_g_trucksalon0, 0);
	TextDrawFont(td_g_trucksalon0, 0);

	td_g_trucksalon1 = TextDrawCreate(487.688842, 341.631561, "usebox");
	TextDrawLetterSize(td_g_trucksalon1, 0.000000, -0.316666);
	TextDrawTextSize(td_g_trucksalon1, 186.399978, 0.000000);
	TextDrawAlignment(td_g_trucksalon1, 1);
	TextDrawColor(td_g_trucksalon1, -1);
	TextDrawUseBox(td_g_trucksalon1, true);
	TextDrawBoxColor(td_g_trucksalon1, -1);
	TextDrawSetShadow(td_g_trucksalon1, 0);
	TextDrawSetOutline(td_g_trucksalon1, 0);
	TextDrawFont(td_g_trucksalon1, 0);

	td_g_trucksalon2 = TextDrawCreate(390.200134, 341.536529, "usebox");
	TextDrawLetterSize(td_g_trucksalon2, 0.000000, -2.414443);
	TextDrawTextSize(td_g_trucksalon2, 385.511322, 0.000000);
	TextDrawAlignment(td_g_trucksalon2, 1);
	TextDrawColor(td_g_trucksalon2, -1);
	TextDrawUseBox(td_g_trucksalon2, true);
	TextDrawBoxColor(td_g_trucksalon2, -1);
	TextDrawSetShadow(td_g_trucksalon2, 0);
	TextDrawSetOutline(td_g_trucksalon2, 0);
	TextDrawFont(td_g_trucksalon2, 0);

	td_g_trucksalon3 = TextDrawCreate(191.600036, 406.833953, "POMOC: ~r~Y ~w~- Wyjscie z wyboru pojazdu ~y~| ~r~Strzalki (lewo/prawo)~w~ - Wybor pojazdu ~y~| ~r~ENTER ~w~- Zakup pojazdu");
	TextDrawLetterSize(td_g_trucksalon3, 0.177333, 0.833422);
	TextDrawAlignment(td_g_trucksalon3, 1);
	TextDrawColor(td_g_trucksalon3, 16711935);
	TextDrawSetShadow(td_g_trucksalon3, 0);
	TextDrawSetOutline(td_g_trucksalon3, -1);
	TextDrawBackgroundColor(td_g_trucksalon3, 51);
	TextDrawFont(td_g_trucksalon3, 1);
	TextDrawSetProportional(td_g_trucksalon3, 1);

	td_g_confirmcargo0 = TextDrawCreate(416.266754, 192.547103, "tlo");
	TextDrawLetterSize(td_g_confirmcargo0, 0.000000, 11.851236);
	TextDrawTextSize(td_g_confirmcargo0, 221.155517, 0.000000);
	TextDrawAlignment(td_g_confirmcargo0, 1);
	TextDrawColor(td_g_confirmcargo0, 0);
	TextDrawUseBox(td_g_confirmcargo0, true);
	TextDrawBoxColor(td_g_confirmcargo0, 102);
	TextDrawSetShadow(td_g_confirmcargo0, 0);
	TextDrawSetOutline(td_g_confirmcargo0, 0);
	TextDrawFont(td_g_confirmcargo0, 0);

	td_g_confirmcargo1 = TextDrawCreate(319.377838, 182.385864, "Potwierdzenie zlecenia");
	TextDrawLetterSize(td_g_confirmcargo1, 0.449999, 1.600000);
	TextDrawAlignment(td_g_confirmcargo1, 2);
	TextDrawColor(td_g_confirmcargo1, 255);
	TextDrawSetShadow(td_g_confirmcargo1, 0);
	TextDrawSetOutline(td_g_confirmcargo1, 1);
	TextDrawBackgroundColor(td_g_confirmcargo1, 8388863);
	TextDrawFont(td_g_confirmcargo1, 3);
	TextDrawSetProportional(td_g_confirmcargo1, 1);

	td_g_confirmcargo6 = TextDrawCreate(298.844696, 201.805801, "tlozielonemodel");
	TextDrawLetterSize(td_g_confirmcargo6, 0.000000, 4.011724);
	TextDrawTextSize(td_g_confirmcargo6, 224.355682, 0.000000);
	TextDrawAlignment(td_g_confirmcargo6, 1);
	TextDrawColor(td_g_confirmcargo6, 0);
	TextDrawUseBox(td_g_confirmcargo6, true);
	TextDrawBoxColor(td_g_confirmcargo6, 8388863);
	TextDrawSetShadow(td_g_confirmcargo6, 0);
	TextDrawSetOutline(td_g_confirmcargo6, 0);
	TextDrawFont(td_g_confirmcargo6, 0);

	td_g_confirmcargo2 = TextDrawCreate(298.155914, 202.805908, "tloczarnemodel");
	TextDrawLetterSize(td_g_confirmcargo2, 0.000000, 3.807283);
	TextDrawTextSize(td_g_confirmcargo2, 225.289047, 0.000000);
	TextDrawAlignment(td_g_confirmcargo2, 1);
	TextDrawColor(td_g_confirmcargo2, 0);
	TextDrawUseBox(td_g_confirmcargo2, true);
	TextDrawBoxColor(td_g_confirmcargo2, 255);
	TextDrawSetShadow(td_g_confirmcargo2, 0);
	TextDrawSetOutline(td_g_confirmcargo2, 0);
	TextDrawFont(td_g_confirmcargo2, 0);

	td_g_confirmcargo3 = TextDrawCreate(233.644119, 285.177032, "AKCEPTUJ");
	TextDrawLetterSize(td_g_confirmcargo3, 0.394888, 1.571627);
	TextDrawTextSize(td_g_confirmcargo3, 293.244354, 15.0);
	TextDrawAlignment(td_g_confirmcargo3, 1);
	TextDrawColor(td_g_confirmcargo3, -1);
	TextDrawUseBox(td_g_confirmcargo3, true);
	TextDrawBoxColor(td_g_confirmcargo3, 8388863);
	TextDrawSetShadow(td_g_confirmcargo3, 0);
	TextDrawSetOutline(td_g_confirmcargo3, -1);
	TextDrawBackgroundColor(td_g_confirmcargo3, 51);
	TextDrawFont(td_g_confirmcargo3, 1);
	TextDrawSetProportional(td_g_confirmcargo3, 1);
	TextDrawSetSelectable(td_g_confirmcargo3, true);
	
	td_g_confirmcargo4 = TextDrawCreate(349.844146, 285.131591, "ANULUJ");
	TextDrawLetterSize(td_g_confirmcargo4, 0.394621, 1.571624);
	TextDrawTextSize(td_g_confirmcargo4, 398.133117, 15.0);
	TextDrawAlignment(td_g_confirmcargo4, 1);
	TextDrawColor(td_g_confirmcargo4, -1);
	TextDrawUseBox(td_g_confirmcargo4, true);
	TextDrawBoxColor(td_g_confirmcargo4, -16776961);
	TextDrawSetShadow(td_g_confirmcargo4, 0);
	TextDrawSetOutline(td_g_confirmcargo4, -1);
	TextDrawBackgroundColor(td_g_confirmcargo4, 51);
	TextDrawFont(td_g_confirmcargo4, 1);
	TextDrawSetProportional(td_g_confirmcargo4, 1);
	TextDrawSetSelectable(td_g_confirmcargo4, true);

	td_g_confirmcargo5 = TextDrawCreate(318.577575, 276.266571, "(Uzyj kursora)____________________________(Klawisz: ESC)");
	TextDrawLetterSize(td_g_confirmcargo5, 0.178755, 0.656711);
	TextDrawAlignment(td_g_confirmcargo5, 2);
	TextDrawColor(td_g_confirmcargo5, -2139062017);
	TextDrawSetShadow(td_g_confirmcargo5, 0);
	TextDrawSetOutline(td_g_confirmcargo5, 0);
	TextDrawBackgroundColor(td_g_confirmcargo5, 51);
	TextDrawFont(td_g_confirmcargo5, 1);
	TextDrawSetProportional(td_g_confirmcargo5, 1);

	td_g_delivered0 = TextDrawCreate(423.700012, 181.574966, "usebox");
	TextDrawLetterSize(td_g_delivered0, 0.000000, 13.618520);
	TextDrawTextSize(td_g_delivered0, 212.199966, 0.000000);
	TextDrawAlignment(td_g_delivered0, 1);
	TextDrawColor(td_g_delivered0, 0);
	TextDrawUseBox(td_g_delivered0, true);
	TextDrawBoxColor(td_g_delivered0, 102);
	TextDrawSetShadow(td_g_delivered0, 0);
	TextDrawSetOutline(td_g_delivered0, 0);
	TextDrawFont(td_g_delivered0, 0);

	td_g_delivered1 = TextDrawCreate(320.250000, 161.641586, "SUKCES");
	TextDrawLetterSize(td_g_delivered1, 1.141722, 3.332173);
	TextDrawAlignment(td_g_delivered1, 2);
	TextDrawColor(td_g_delivered1, 255);
	TextDrawSetShadow(td_g_delivered1, 0);
	TextDrawSetOutline(td_g_delivered1, 1);
	TextDrawBackgroundColor(td_g_delivered1, 16711935);
	TextDrawFont(td_g_delivered1, 3);
	TextDrawSetProportional(td_g_delivered1, 1);

	td_g_delivered2 = TextDrawCreate(320.350036, 193.141601, "Dostarczenie ladunku powiodlo sie!");
	TextDrawLetterSize(td_g_delivered2, 0.262099, 1.293750);
	TextDrawAlignment(td_g_delivered2, 2);
	TextDrawColor(td_g_delivered2, 16711935);
	TextDrawSetShadow(td_g_delivered2, 0);
	TextDrawSetOutline(td_g_delivered2, 1);
	TextDrawBackgroundColor(td_g_delivered2, 51);
	TextDrawFont(td_g_delivered2, 1);
	TextDrawSetProportional(td_g_delivered2, 1);

	td_g_delivered3 = TextDrawCreate(422.149963, 209.749984, "usebox");
	TextDrawLetterSize(td_g_delivered3, 0.000000, -0.391479);
	TextDrawTextSize(td_g_delivered3, 213.650070, 0.000000);
	TextDrawAlignment(td_g_delivered3, 1);
	TextDrawColor(td_g_delivered3, 0);
	TextDrawUseBox(td_g_delivered3, true);
	TextDrawBoxColor(td_g_delivered3, 16711935);
	TextDrawSetShadow(td_g_delivered3, 0);
	TextDrawSetOutline(td_g_delivered3, 0);
	TextDrawFont(td_g_delivered3, 0);

	td_g_delivered4 = TextDrawCreate(422.499969, 288.099945, "usebox");
	TextDrawLetterSize(td_g_delivered4, 0.000000, -0.386479);
	TextDrawTextSize(td_g_delivered4, 213.550079, 0.000000);
	TextDrawAlignment(td_g_delivered4, 1);
	TextDrawColor(td_g_delivered4, 0);
	TextDrawUseBox(td_g_delivered4, true);
	TextDrawBoxColor(td_g_delivered4, 16711935);
	TextDrawSetShadow(td_g_delivered4, 0);
	TextDrawSetOutline(td_g_delivered4, 0);
	TextDrawFont(td_g_delivered4, 0);

	td_g_delivered5 = TextDrawCreate(216.249893, 288.691741, "Kasa:");
	TextDrawLetterSize(td_g_delivered5, 0.369999, 1.434916);
	TextDrawAlignment(td_g_delivered5, 1);
	TextDrawColor(td_g_delivered5, 255);
	TextDrawSetShadow(td_g_delivered5, 0);
	TextDrawSetOutline(td_g_delivered5, 1);
	TextDrawBackgroundColor(td_g_delivered5, 8388863);
	TextDrawFont(td_g_delivered5, 1);
	TextDrawSetProportional(td_g_delivered5, 1);

	td_g_delivered6 = TextDrawCreate(327.649871, 288.525085, "Score:");
	TextDrawLetterSize(td_g_delivered6, 0.369999, 1.434916);
	TextDrawAlignment(td_g_delivered6, 1);
	TextDrawColor(td_g_delivered6, 255);
	TextDrawSetShadow(td_g_delivered6, 0);
	TextDrawSetOutline(td_g_delivered6, 1);
	TextDrawBackgroundColor(td_g_delivered6, -2147483393);
	TextDrawFont(td_g_delivered6, 1);
	TextDrawSetProportional(td_g_delivered6, 1);

	td_g_delivered7 = TextDrawCreate(423.700073, 310.258422, "usebox");
	TextDrawLetterSize(td_g_delivered7, 0.000000, 0.902777);
	TextDrawTextSize(td_g_delivered7, 212.500015, 0.000000);
	TextDrawAlignment(td_g_delivered7, 1);
	TextDrawColor(td_g_delivered7, 0);
	TextDrawUseBox(td_g_delivered7, true);
	TextDrawBoxColor(td_g_delivered7, 102);
	TextDrawSetShadow(td_g_delivered7, 0);
	TextDrawSetOutline(td_g_delivered7, 0);
	TextDrawFont(td_g_delivered7, 0);

	td_g_delivered8 = TextDrawCreate(315.949920, 307.358306, "Wcisnij klawisz spacji aby zamknac okno.");
	TextDrawLetterSize(td_g_delivered8, 0.216450, 1.229583);
	TextDrawAlignment(td_g_delivered8, 2);
	TextDrawColor(td_g_delivered8, -16776961);
	TextDrawSetShadow(td_g_delivered8, 0);
	TextDrawSetOutline(td_g_delivered8, 1);
	TextDrawBackgroundColor(td_g_delivered8, 51);
	TextDrawFont(td_g_delivered8, 1);
	TextDrawSetProportional(td_g_delivered8, 1);

	td_g_saction0 = TextDrawCreate(648.444396, 135.800354, "usebox");
	TextDrawLetterSize(td_g_saction0, 0.000000, 1.357900);
	TextDrawTextSize(td_g_saction0, 493.866516, 0.000000);
	TextDrawAlignment(td_g_saction0, 1);
	TextDrawColor(td_g_saction0, 12225791);
	TextDrawUseBox(td_g_saction0, true);
	TextDrawBoxColor(td_g_saction0, 65535);
	TextDrawSetShadow(td_g_saction0, 0);
	TextDrawSetOutline(td_g_saction0, 0);
	TextDrawFont(td_g_saction0, 0);

	td_g_saction1 = TextDrawCreate(651.177978, 137.347854, "usebox");
	TextDrawLetterSize(td_g_saction1, 0.000000, 1.015678);
	TextDrawTextSize(td_g_saction1, 495.066558, 0.000000);
	TextDrawAlignment(td_g_saction1, 1);
	TextDrawColor(td_g_saction1, 0);
	TextDrawUseBox(td_g_saction1, true);
	TextDrawBoxColor(td_g_saction1, 255);
	TextDrawSetShadow(td_g_saction1, 0);
	TextDrawSetOutline(td_g_saction1, 0);
	TextDrawFont(td_g_saction1, 0);

	td_g_taxi0 = TextDrawCreate(404.577819, 339.640380, "usebox");
	TextDrawLetterSize(td_g_taxi0, 0.000000, 7.426544);
	TextDrawTextSize(td_g_taxi0, 228.133346, 0.000000);
	TextDrawAlignment(td_g_taxi0, 1);
	TextDrawColor(td_g_taxi0, 0);
	TextDrawUseBox(td_g_taxi0, true);
	TextDrawBoxColor(td_g_taxi0, 102);
	TextDrawSetShadow(td_g_taxi0, 0);
	TextDrawSetOutline(td_g_taxi0, 0);
	TextDrawFont(td_g_taxi0, 0);

	td_g_taxi1 = TextDrawCreate(315.911071, 330.723602, "TAXOMETR");
	TextDrawLetterSize(td_g_taxi1, 0.449999, 1.600000);
	TextDrawAlignment(td_g_taxi1, 2);
	TextDrawColor(td_g_taxi1, 255);
	TextDrawSetShadow(td_g_taxi1, 0);
	TextDrawSetOutline(td_g_taxi1, 1);
	TextDrawBackgroundColor(td_g_taxi1, -65281);
	TextDrawFont(td_g_taxi1, 3);
	TextDrawSetProportional(td_g_taxi1, 1);

	td_g_taxi2 = TextDrawCreate(357.333099, 337.095123, "fiskalny");
	TextDrawLetterSize(td_g_taxi2, 0.150444, 1.005156);
	TextDrawAlignment(td_g_taxi2, 1);
	TextDrawColor(td_g_taxi2, -65281);
	TextDrawSetShadow(td_g_taxi2, 0);
	TextDrawSetOutline(td_g_taxi2, 1);
	TextDrawBackgroundColor(td_g_taxi2, 51);
	TextDrawFont(td_g_taxi2, 1);
	TextDrawSetProportional(td_g_taxi2, 1);

	td_g_taxi3 = TextDrawCreate(394.177673, 380.607513, "usebox");
	TextDrawLetterSize(td_g_taxi3, 0.000000, -0.316666);
	TextDrawTextSize(td_g_taxi3, 238.177825, 0.000000);
	TextDrawAlignment(td_g_taxi3, 1);
	TextDrawColor(td_g_taxi3, -65281);
	TextDrawUseBox(td_g_taxi3, true);
	TextDrawBoxColor(td_g_taxi3, -65281);
	TextDrawSetShadow(td_g_taxi3, 0);
	TextDrawSetOutline(td_g_taxi3, 0);
	TextDrawFont(td_g_taxi3, 0);

	td_g_taxi4 = TextDrawCreate(394.066772, 387.979339, "usebox");
	TextDrawLetterSize(td_g_taxi4, 0.000000, -0.316666);
	TextDrawTextSize(td_g_taxi4, 238.133453, 0.000000);
	TextDrawAlignment(td_g_taxi4, 1);
	TextDrawColor(td_g_taxi4, -65281);
	TextDrawUseBox(td_g_taxi4, true);
	TextDrawBoxColor(td_g_taxi4, -65281);
	TextDrawSetShadow(td_g_taxi4, 0);
	TextDrawSetOutline(td_g_taxi4, 0);
	TextDrawFont(td_g_taxi4, 0);

	td_g_taxi5 = TextDrawCreate(315.110931, 378.759155, "DO ZAPLATY");
	TextDrawLetterSize(td_g_taxi5, 0.264311, 0.816497);
	TextDrawAlignment(td_g_taxi5, 2);
	TextDrawColor(td_g_taxi5, -16776961);
	TextDrawSetShadow(td_g_taxi5, 0);
	TextDrawSetOutline(td_g_taxi5, 1);
	TextDrawBackgroundColor(td_g_taxi5, 51);
	TextDrawFont(td_g_taxi5, 1);
	TextDrawSetProportional(td_g_taxi5, 1);

	td_g_dokument0 = TextDrawCreate(403.733337, 188.166656, "usebox");
	TextDrawLetterSize(td_g_dokument0, 0.000000, 9.684319);
	TextDrawTextSize(td_g_dokument0, 234.000000, 0.000000);
	TextDrawAlignment(td_g_dokument0, 1);
	TextDrawColor(td_g_dokument0, 0);
	TextDrawUseBox(td_g_dokument0, true);
	TextDrawBoxColor(td_g_dokument0, 12225791);
	TextDrawSetShadow(td_g_dokument0, 0);
	TextDrawSetOutline(td_g_dokument0, 0);
	TextDrawFont(td_g_dokument0, 0);
	
	td_g_dokument1 = TextDrawCreate(401.400329, 191.058227, "usebox");
	TextDrawLetterSize(td_g_dokument1, 0.000000, 9.119876);
	TextDrawTextSize(td_g_dokument1, 236.088882, 0.000000);
	TextDrawAlignment(td_g_dokument1, 1);
	TextDrawColor(td_g_dokument1, 255);
	TextDrawUseBox(td_g_dokument1, true);
	TextDrawBoxColor(td_g_dokument1, 255);
	TextDrawSetShadow(td_g_dokument1, 0);
	TextDrawSetOutline(td_g_dokument1, 0);
	TextDrawFont(td_g_dokument1, 0);
	
	td_g_dokument2 = TextDrawCreate(275.266723, 211.268066, "usebox");
	TextDrawLetterSize(td_g_dokument2, 0.000000, 6.168765);
	TextDrawTextSize(td_g_dokument2, 271.111328, 0.000000);
	TextDrawAlignment(td_g_dokument2, 1);
	TextDrawColor(td_g_dokument2, 0);
	TextDrawUseBox(td_g_dokument2, true);
	TextDrawBoxColor(td_g_dokument2, 12225791);
	TextDrawSetShadow(td_g_dokument2, 0);
	TextDrawSetOutline(td_g_dokument2, 0);
	TextDrawFont(td_g_dokument2, 0);
	
	td_g_dokument3 = TextDrawCreate(395.066406, 203.855667, "usebox");
	TextDrawLetterSize(td_g_dokument3, 0.000000, -0.346789);
	TextDrawTextSize(td_g_dokument3, 243.289016, 0.000000);
	TextDrawAlignment(td_g_dokument3, 1);
	TextDrawColor(td_g_dokument3, 0);
	TextDrawUseBox(td_g_dokument3, true);
	TextDrawBoxColor(td_g_dokument3, 12225791);
	TextDrawSetShadow(td_g_dokument3, 0);
	TextDrawSetOutline(td_g_dokument3, 0);
	TextDrawFont(td_g_dokument3, 0);
	
	td_g_dokument4 = TextDrawCreate(319.377532, 186.716461, "Dokument tozsamosci Highway Life");
	TextDrawLetterSize(td_g_dokument4, 0.170711, 1.732408);
	TextDrawAlignment(td_g_dokument4, 2);
	TextDrawColor(td_g_dokument4, 16777215);
	TextDrawSetShadow(td_g_dokument4, 0);
	TextDrawSetOutline(td_g_dokument4, 1);
	TextDrawBackgroundColor(td_g_dokument4, 51);
	TextDrawFont(td_g_dokument4, 2);
	TextDrawSetProportional(td_g_dokument4, 1);
	
	td_g_dokument5 = TextDrawCreate(395.710876, 249.058364, "usebox");
	TextDrawLetterSize(td_g_dokument5, 0.000000, -0.315678);
	TextDrawTextSize(td_g_dokument5, 277.200012, 0.000000);
	TextDrawAlignment(td_g_dokument5, 1);
	TextDrawColor(td_g_dokument5, 0);
	TextDrawUseBox(td_g_dokument5, true);
	TextDrawBoxColor(td_g_dokument5, 12225791);
	TextDrawSetShadow(td_g_dokument5, 0);
	TextDrawSetOutline(td_g_dokument5, 0);
	TextDrawFont(td_g_dokument5, 0);
	
	td_g_dokument6 = TextDrawCreate(278.844390, 251.825744, "Uprawnienia:");
	TextDrawLetterSize(td_g_dokument6, 0.198400, 1.688604);
	TextDrawAlignment(td_g_dokument6, 1);
	TextDrawColor(td_g_dokument6, 255);
	TextDrawSetShadow(td_g_dokument6, 0);
	TextDrawSetOutline(td_g_dokument6, 1);
	TextDrawBackgroundColor(td_g_dokument6, -1061109505);
	TextDrawFont(td_g_dokument6, 3);
	TextDrawSetProportional(td_g_dokument6, 1);

	td_g_dokument7 = TextDrawCreate(237.777664, 282.090850, "Aby zamknac wcisnij ~r~~h~~h~SPACJE");
	TextDrawLetterSize(td_g_dokument7, 0.325155, 1.156977);
	TextDrawTextSize(td_g_dokument7, 400.266754, 2.588443);
	TextDrawAlignment(td_g_dokument7, 1);
	TextDrawColor(td_g_dokument7, -1);
	TextDrawUseBox(td_g_dokument7, true);
	TextDrawBoxColor(td_g_dokument7, 12225573);
	TextDrawSetShadow(td_g_dokument7, 0);
	TextDrawSetOutline(td_g_dokument7, 1);
	TextDrawBackgroundColor(td_g_dokument7, 51);
	TextDrawFont(td_g_dokument7, 1);
	TextDrawSetProportional(td_g_dokument7, 1);

	td_g_shoot0 = TextDrawCreate(324.000000, 170.187500, "~l~/___~r~\\~n~~n~~r~\\___~l~/");
	TextDrawLetterSize(td_g_shoot0, 0.416499, 0.615625);
	TextDrawAlignment(td_g_shoot0, 1);
	TextDrawColor(td_g_shoot0, -2147483393);
	TextDrawSetShadow(td_g_shoot0, 0);
	TextDrawSetOutline(td_g_shoot0, 0);
	TextDrawBackgroundColor(td_g_shoot0, 51);
	TextDrawFont(td_g_shoot0, 1);
	TextDrawSetProportional(td_g_shoot0, 1);

	td_g_shoot1 = TextDrawCreate(324.000000, 170.187500, "~r~/___~l~\\~n~~n~~l~\\___~r~/");
	TextDrawLetterSize(td_g_shoot1, 0.416499, 0.615625);
	TextDrawAlignment(td_g_shoot1, 1);
	TextDrawColor(td_g_shoot1, -2147483393);
	TextDrawSetShadow(td_g_shoot1, 0);
	TextDrawSetOutline(td_g_shoot1, 0);
	TextDrawBackgroundColor(td_g_shoot1, 51);
	TextDrawFont(td_g_shoot1, 1);
	TextDrawSetProportional(td_g_shoot1, 1);

	td_g_limit0 = TextDrawCreate(457.822540-18.0, 15.431127, "LD_POOL:ball");
	TextDrawLetterSize(td_g_limit0, 0.000000, 0.000000);
	TextDrawTextSize(td_g_limit0, 36.000007, 37.831111);
	TextDrawAlignment(td_g_limit0, 1);
	TextDrawColor(td_g_limit0, -16776961);
	TextDrawSetShadow(td_g_limit0, 0);
	TextDrawSetOutline(td_g_limit0, 0);
	TextDrawFont(td_g_limit0, 4);
	
	td_g_limit1 = TextDrawCreate(461.711547-18.0, 19.865783, "LD_POOL:ball");
	TextDrawLetterSize(td_g_limit1, 0.000000, 0.000000);
	TextDrawTextSize(td_g_limit1, 28.444454, 28.871114);
	TextDrawAlignment(td_g_limit1, 1);
	TextDrawColor(td_g_limit1, -1);
	TextDrawSetShadow(td_g_limit1, 0);
	TextDrawSetOutline(td_g_limit1, 0);
	TextDrawFont(td_g_limit1, 4);
	//printf("[DEBUG]TextDrawCount (global): %d", td_g_taxi5);//ustawić ostatni TD
	return 1;
}